In [482]:
ex_id = '03'
if ex_id == '03':
    mask_id = '3'

orientation = 'WE'
mask_prep_string = rf"""/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python -B \
  rivgraph_centerline/run_workflow.py prepare-mask \
  --name {ex_id} \
  --source-mask /Volumes/PhD/river_hierarchy/data/water_masks/example_{mask_id}_2026_FebApr_persistent_mask_uint8.tif"""
print(mask_prep_string)

apply_edits_string = rf"""/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python -B \
  rivgraph_centerline/run_workflow.py apply-edits \
  --name {ex_id}"""
print()
print(apply_edits_string)

run_rivgraph = rf"""MPLCONFIGDIR=/tmp/matplotlib-rivgraph \
/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python -B \
  rivgraph_centerline/run_workflow.py run-rivgraph \
  --name {ex_id} \
  --exit-sides {orientation} \
  --run-dir rivgraph_centerline/outputs/runs/{ex_id} \
  --assign-flow"""
print()
print(run_rivgraph)

/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python -B \
  rivgraph_centerline/run_workflow.py prepare-mask \
  --name 03 \
  --source-mask /Volumes/PhD/river_hierarchy/data/water_masks/example_3_2026_FebApr_persistent_mask_uint8.tif

/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python -B \
  rivgraph_centerline/run_workflow.py apply-edits \
  --name 03

MPLCONFIGDIR=/tmp/matplotlib-rivgraph \
/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python -B \
  rivgraph_centerline/run_workflow.py run-rivgraph \
  --name 03 \
  --exit-sides WE \
  --run-dir rivgraph_centerline/outputs/runs/03 \
  --assign-flow

In [491]:
# Level detection Compound
nv = 'compound-bubbles' #independent-units
ex_id = '03'

if nv == 'compound-bubbles':
    nv_ = 'compound_bubbles'
    nvs = 'compound_bubbles'

elif nv == 'independent-units':
    nv_ = 'independent_units'
    nvs = 'indep'

orientation = 'SN' 
# 2 EW
# 3 SN

level_detection_string = rf"""/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python \
  network_variants/run_collapse_experiment.py \
  compound-bubbles \
  --cleaned-mask rivgraph_centerline/outputs/runs/{ex_id}/masks_cleaned/{ex_id}_cleaned.tif \
  --reviewed-links /Users/6256481/Code/river-hierarchy/rivgraph_centerline/outputs/runs/{ex_id}/rivgraph/{ex_id}_links.gpkg \
  --reviewed-nodes /Users/6256481/Code/river-hierarchy/rivgraph_centerline/outputs/runs/{ex_id}/rivgraph/{ex_id}_nodes.gpkg \
  --exit-sides {orientation} \
  --experiment-id {ex_id}_{nv_} \
  --output-dir network_variants/output/{ex_id}_{nvs} \
  --sword-node-source /Volumes/PhD/SWORD/v17c/ \
  --sword-example-stations-source SWORD_gauge_match/outputs/hierarchy_examples_filtered_subdaily_manual_updates_final.gpkg \
  --sword-station-match-source SWORD_gauge_match/outputs/selected_event_stations_same_main_path.gpkg \
  --sword-reach-buffer-steps 2 \
  --sword-wse-field wse_obs_p50
"""
print(level_detection_string)

/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python \
  network_variants/run_collapse_experiment.py \
  compound-bubbles \
  --cleaned-mask rivgraph_centerline/outputs/runs/03/masks_cleaned/03_cleaned.tif \
  --reviewed-links /Users/6256481/Code/river-hierarchy/rivgraph_centerline/outputs/runs/03/rivgraph/03_links.gpkg \
  --reviewed-nodes /Users/6256481/Code/river-hierarchy/rivgraph_centerline/outputs/runs/03/rivgraph/03_nodes.gpkg \
  --exit-sides SN \
  --experiment-id 03_compound_bubbles \
  --output-dir network_variants/output/03_compound_bubbles \
  --sword-node-source /Volumes/PhD/SWORD/v17c/ \
  --sword-example-stations-source SWORD_gauge_match/outputs/hierarchy_examples_filtered_subdaily_manual_updates_final.gpkg \
  --sword-station-match-source SWORD_gauge_match/outputs/selected_event_stations_same_main_path.gpkg \
  --sword-reach-buffer-steps 2 \
  --sword-wse-field wse_obs_p50

In [538]:
ex_id       = '03'
STATION_KEY = 'BR:3652880'
nvs         = 'compound_bubbles'#'indep'
start_time  = '2023-02-01T00:00:00Z'
end_time    = '2023-03-10T00:00:00Z'  
forcing_time = '18' 

# ex_id       = '05'
# STATION_KEY = 'BR:3649421'
# nvs         = 'indep' #'compound_bubbles'
# start_time  = '2023-12-17T00:00:00Z' 
# end_time    = '2024-01-15T00:00:00Z'  
# forcing_time = '15' 


base_rapid_prep = rf"""/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python \
  RAPID/run_prepare_experiment.py \
  /Users/6256481/Code/river-hierarchy/network_variants/output/{ex_id}_{nvs} \
  --forcing-path SWORD_gauge_match/outputs/subdaily_values/BR/subdaily_timeseries.parquet \
  --forcing-station-key {STATION_KEY} \
  --station-key-column station_key \
  --time-column time \
  --discharge-column discharge \
  --forcing-start-time {start_time} \
  --forcing-end-time {end_time} \
  --forcing-resample-minutes {forcing_time} \
  --forcing-output-cache-dir SWORD_gauge_match/outputs/rapid_forcing_cache \
  --kb-mode based_reference_section \
  --kb-model-path RAPID/assets/based_model_v2.ubj \
  --kb-width-sample-field width_wet \
  --kb-width-percentile 90 \
  --use-celerity-capping \
  --min-celerity-mps 0.05 \
  --max-celerity-mps 2.524 \
  --target-subreach-length-m 200 \
  --min-effective-length-for-k-m 200 \
  --max-slope-for-k 0.005 \
  --section-slope-ratio-max 5 \
  --vary-width-by-subreach \
  --subreach-width-sample-field width_wet"""


print(base_rapid_prep)
print()
run_rapid_string = rf"""/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python \
  RAPID/run_rapid_experiment.py \
  /Users/6256481/Code/river-hierarchy/network_variants/output/{ex_id}_{nvs}"""
print(run_rapid_string)

/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python \
  RAPID/run_prepare_experiment.py \
  /Users/6256481/Code/river-hierarchy/network_variants/output/03_compound_bubbles \
  --forcing-path SWORD_gauge_match/outputs/subdaily_values/BR/subdaily_timeseries.parquet \
  --forcing-station-key BR:3652880 \
  --station-key-column station_key \
  --time-column time \
  --discharge-column discharge \
  --forcing-start-time 2023-02-01T00:00:00Z \
  --forcing-end-time 2023-03-10T00:00:00Z \
  --forcing-resample-minutes 18 \
  --forcing-output-cache-dir SWORD_gauge_match/outputs/rapid_forcing_cache \
  --kb-mode based_reference_section \
  --kb-model-path RAPID/assets/based_model_v2.ubj \
  --kb-width-sample-field width_wet \
  --kb-width-percentile 90 \
  --use-celerity-capping \
  --min-celerity-mps 0.05 \
  --max-celerity-mps 2.524 \
  --target-subreach-length-m 200 \
  --min-effective-length-for-k-m 200 \
  --max-slope-for-k 0.005 \
  --section-slope-ratio-max 5 \
  --vary-width-by-subreach \
  --subreach-width-sample-field width_wet

/opt/anaconda3/envs/river-hierarchy-rivgraph/bin/python \
  RAPID/run_rapid_experiment.py \
  /Users/6256481/Code/river-hierarchy/network_variants/output/03_compound_bubbles

# RAPID example_id matching to gauging station names

In [24]:
import geopandas as gpd
import pandas as pd

import plotly.graph_objects as go

import plotly.express as px

In [438]:
p = '/Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/'
df_ex = gpd.read_file(p +'hierarchy_examples_filtered_subdaily_manual_updates_final.gpkg')

dfsub = pd.read_parquet(p + f'subdaily_values/BR/subdaily_timeseries.parquet')
# dfsub2 = pd.read_parquet(p + f'subdaily_values/LA/subdaily_timeseries.parquet')

In [447]:
stations = df_ex.loc[df_ex['example_ids'] == '10', 'station_key'].to_list()
display(stations)

['BR:3635040', 'BR:3635041']

In [448]:
stat1 = dfsub[dfsub['station_key'] == stations[0]]
stat2 = dfsub[dfsub['station_key'] == stations[1]]
# stat3 = dfsub[dfsub['station_key'] == stations[2]]
# stat4 = dfsub[dfsub['station_key'] == stations[3]]

# stat3 = dfsub2[dfsub2['station_key'] == stations[2]]

# RAPID Hydrograph Peak selection

In [449]:
p1 = stat1.copy()
p2 = stat2.copy()
# p3 = stat3.copy()
# p4 = stat4.copy()


# tstart = '2024-10-13 00:01:00+0000'
# tend   = '2025-10-22 00:00:00+0000'
# p1 = p1[(p1['time'] > tstart) & (p1['time'] < tend)]
# p2 = p2[(p2['time'] > tstart) & (p2['time'] < tend)]
# p3 = p3[(p3['time'] > tstart) & (p3['time'] < tend)]
# p4 = p4[(p4['time'] > tstart) & (p4['time'] < tend)]

stationList = [p1,p2]
# stationList = [p1,p2, p3, p4]

In [457]:
np.sqrt(2)

np.float64(1.4142135623730951)

In [450]:
fig = go.Figure()
for p in stationList:
    fig.add_trace(go.Scatter(
        x=p["time"],
        y=p["discharge"],
        mode="markers",
        name=p['station_key'].iloc[0],
        hovertemplate=f"{p['station_key'].iloc[0]}" +"<br>time: %{x}<br>discharge: %{y}<extra></extra>"
    ))

# fig.add_trace(go.Scatter(
#     x=p2["time"],
#     y=p2["discharge"],
#     mode="markers",
#     name=f"{p2['station_key'].iloc[0]}",
#     hovertemplate=f"{p2['station_key'].iloc[0]}"+"<br>time: %{x}<br>discharge: %{y}<extra></extra>"
# ))

fig.update_layout(
    title="Discharge over Time",
    xaxis_title="time",
    yaxis_title="discharge"
)

fig.show('browser')

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Example 03:
- Peak  tstart = '2023-02-12 00:00:00+0000' tend   = '2023-02-23 00:00:00+0000'
- Exact start 2023-02-14T18:00:00Z --> 8 hour window
- Exact end 2023-02-18T16:00:00Z --> 10 hour window

## Normalize peak files to 30 min or one hour for RAPID
- make sure all timesteps are equal

In [433]:
tstart = "2023-02-12 00:00:00+0000"
tend   = "2023-02-23 00:00:00+0000"

p1 = stat1.copy()
p1["time"] = pd.to_datetime(p1["time"], utc=True)

p1 = p1[(p1["time"] > tstart) & (p1["time"] < tend)].copy()
p1 = p1.sort_values("time")

# set time index
p1i = p1.set_index("time")

# 30-minute discharge series
p1_30min = (
    p1i["discharge"]
    .resample("15min")
    .mean()
    .interpolate("time")
    .reset_index()
)

# hourly discharge series
p1_1h = (
    p1i["discharge"]
    .resample("1h")
    .mean()
    .interpolate("time")
    .reset_index()
)

p1_30min.to_csv(p + "subdaily_values/BR/Ex_03_2023_02_30min.csv", index=False)
p1_1h.to_csv(p + "subdaily_values/BR/Ex_03_2023_02_1h.csv", index=False)

# RAPID Peak plot

In [520]:
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.io import netcdf_file

ex_id = '03'
nv = 'indep' #'compound_bubbles'

exp_dir = Path(f"/Users/6256481/Code/river-hierarchy/network_variants/output/{ex_id}_{nv}")
run_registry = pd.read_csv(exp_dir / "rapid_run_registry.csv")

series_by_state = {}

for row in run_registry.itertuples(index=False):
    if row.status != "ran":
        continue

    qout_path = Path(row.qout_nc)
    prep_manifest_path = Path(row.rapid_prep_dir) / "rapid_prep_manifest.json"

    with netcdf_file(qout_path, "r", mmap=False) as ds:
        rivid = np.array(ds.variables["rivid"].data).copy()
        time = np.array(ds.variables["time"].data).copy()
        qout = np.array(ds.variables["Qout"].data).copy()

    riv = pd.read_csv(Path(row.rapid_prep_dir) / "riv.csv", header=None)[0].to_numpy()
    final_reach_id = int(riv[-1])
    final_idx = int(np.where(rivid == final_reach_id)[0][0])

    ts = pd.DataFrame(
        {
            "time_seconds": time,
            "q_cms": qout[:, final_idx],
        }
    )
    ts["state_id"] = row.state_id
    ts["final_reach_id"] = final_reach_id

    series_by_state[row.state_id] = ts

# example: one state
# print(series_by_state["S001_unit_5"].head())

# combine all states into one long table
all_outlet_ts = pd.concat(series_by_state.values(), ignore_index=True)
print(all_outlet_ts.head())

   time_seconds          q_cms   state_id  final_reach_id
0             0  1.475375e-247  S000_base             746
1          1080  1.270658e-244  S000_base             746
2          2160  5.456054e-242  S000_base             746
3          3240  1.557379e-239  S000_base             746
4          4320  3.324540e-237  S000_base             746

In [521]:
tstart = pd.Timestamp('2023-02-01 00:01:00+0000')

fig = go.Figure()

for k, u in series_by_state.items():
    start = 0
    end  = 0

    if end == 0:
        t_seconds = np.asarray(u["time_seconds"][start::], dtype=np.float64).copy()
        q = np.asarray(u["q_cms"][start::], dtype=np.float64).copy()
    else:
        t_seconds = np.asarray(u["time_seconds"][start:end], dtype=np.float64).copy()
        q = np.asarray(u["q_cms"][start:end], dtype=np.float64).copy()
    state_name = u["state_id"].iloc[0]

    t_hours = t_seconds / 3600.0
    t_datetime = tstart + pd.to_timedelta(t_hours, unit="h")

    fig.add_trace(
        go.Scatter(
            x=t_datetime,
            y=q,
            mode="markers",
            name=state_name,
            customdata=np.column_stack([t_hours]),
            hovertemplate=(
                f"{state_name}"
                + "<br>time: %{x|%Y-%m-%d %H:%M}"
                + "<br>hours since start: %{customdata[0]:.1f}"
                + "<br>discharge: %{y:.2f}"
                + "<extra></extra>"
            ),
        )
    )

fig.update_layout(
    title="Discharge over Time",
    xaxis_title="time",
    yaxis_title="discharge",
)

fig.show(renderer="browser")

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

# RAPID Hydrograph Analysis

Use this notebook after `RAPID/run_rapid_experiment.py` has finished. It reads the per-state outlet hydrographs and hydrograph metrics written under each state's `rapid/run/` folder.

In [493]:
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [522]:
experiment_dir = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/03_indep")
run_registry = pd.read_csv(experiment_dir / "rapid_run_registry.csv")
run_registry.head()

,state_id,rapid_prep_dir,rapid_run_dir,qout_nc,status,hydrograph_status,outlet_hydrograph_csv,hydrograph_metrics_csv,hydrograph_metrics_json,event_definition_version,...,outlet_excess_volume_m3,outlet_reach_count,outlet_reach_ids,hydrograph_duration_seconds,metric_config,fall_time_seconds,fall_time_50_seconds,fall_time_10_seconds,e_folding_time_seconds,rise_rate_cms_per_hour
0,S000_base,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.457795e+08,1,[746],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185724.429126,338007.859584,235304.585060,5.110847
1,S001_unit_28,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.357741e+08,1,[738],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185120.528941,337647.363379,234814.308777,5.092036
2,S002_unit_33,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.427600e+08,1,[741],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",433080.0,184945.450130,337239.407698,234511.510665,5.098017
3,S003_unit_29,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.379520e+08,1,[738],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185410.187725,337852.155781,235055.076056,5.095587
4,S004_unit_2,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.345530e+08,1,[737],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185268.660461,337829.628672,234980.659188,5.093056

In [523]:
metric_cols = [
    "state_id",
    "event_start_time_utc",
    "peak_time_utc",
    "event_end_time_utc",
    "peak_discharge_cms",
    "peak_excess_cms",
    "peak_excess_to_end_baseline_cms",
    "time_to_peak_seconds",
    "event_duration_seconds",
    "fall_time_seconds",
    "fall_time_50_seconds",
    "fall_time_10_seconds",
    "e_folding_time_seconds",
    "lag_to_inflow_peak_seconds",
    "peak_attenuation_ratio",
]
run_registry[metric_cols].sort_values("peak_discharge_cms", ascending=False).head(28)

,state_id,event_start_time_utc,peak_time_utc,event_end_time_utc,peak_discharge_cms,peak_excess_cms,peak_excess_to_end_baseline_cms,time_to_peak_seconds,event_duration_seconds,fall_time_seconds,fall_time_50_seconds,fall_time_10_seconds,e_folding_time_seconds,lag_to_inflow_peak_seconds,peak_attenuation_ratio
44,S046_unit_10,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T20:06:00+00:00,2431.794794,912.728429,1299.364835,645840.0,1081080.0,435240.0,184606.284349,337547.869158,234884.436435,644760.0,0.923987
50,S052_unit_46,2023-02-17T07:48:00+00:00,2023-02-24T18:54:00+00:00,2023-03-01T19:30:00+00:00,2430.016884,911.187722,1297.134010,644760.0,1078920.0,434160.0,184701.469838,337502.843113,234539.533240,643680.0,0.923311
33,S035_unit_1,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:42:00+00:00,2429.512896,916.476336,1295.995996,648000.0,1083240.0,435240.0,184738.211666,337492.366218,234811.578278,646920.0,0.923120
49,S051_unit_51,2023-02-17T07:48:00+00:00,2023-02-24T18:00:00+00:00,2023-03-01T18:36:00+00:00,2429.223832,907.670393,1295.982765,641520.0,1075680.0,434160.0,184650.248823,337399.570562,234413.985386,640440.0,0.923010
43,S045_unit_47,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:42:00+00:00,2427.559255,917.300255,1293.329195,648000.0,1083240.0,435240.0,185356.077945,337955.068841,235111.896711,646920.0,0.922378
32,S034_unit_26,2023-02-17T07:48:00+00:00,2023-02-24T17:42:00+00:00,2023-03-01T18:36:00+00:00,2427.301392,907.494179,1292.967219,640440.0,1075680.0,435240.0,185430.916969,338020.014670,235155.464830,639360.0,0.922280
39,S041_unit_20,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2427.108957,914.958408,1292.571148,646920.0,1081080.0,434160.0,184974.925874,337539.676476,234762.460996,645840.0,0.922206
4,S004_unit_2,2023-02-17T07:48:00+00:00,2023-02-24T18:54:00+00:00,2023-03-01T19:30:00+00:00,2426.954081,912.166395,1292.434312,644760.0,1078920.0,434160.0,185268.660461,337829.628672,234980.659188,643680.0,0.922148
41,S043_unit_12,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T19:48:00+00:00,2426.592603,913.728174,1291.853763,645840.0,1080000.0,434160.0,185255.932711,337787.187889,234972.674676,644760.0,0.922010
1,S001_unit_28,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T19:48:00+00:00,2426.516309,913.511319,1291.765570,645840.0,1080000.0,434160.0,185120.528941,337647.363379,234814.308777,644760.0,0.921981
24,S026_unit_4,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T19:48:00+00:00,2425.831976,914.009416,1290.700609,645840.0,1080000.0,434160.0,185427.557451,337895.709847,235104.191594,644760.0,0.921721
3,S003_unit_29,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2425.483838,915.677012,1290.192766,646920.0,1081080.0,434160.0,185410.187725,337852.155781,235055.076056,645840.0,0.921589
9,S009_unit_25,2023-02-17T07:48:00+00:00,2023-02-24T18:36:00+00:00,2023-03-01T19:12:00+00:00,2425.481613,910.998606,1290.182207,643680.0,1077840.0,434160.0,185400.929375,337842.939900,235050.969502,642600.0,0.921588
13,S013_unit_14,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:24:00+00:00,2425.397330,917.924052,1290.112589,648000.0,1082160.0,434160.0,185685.063013,338118.900507,235289.630260,646920.0,0.921556
45,S047_unit_48,2023-02-17T07:48:00+00:00,2023-02-24T22:12:00+00:00,2023-03-01T22:48:00+00:00,2425.313078,935.886629,1289.797327,656640.0,1090800.0,434160.0,184890.943265,337293.546087,234616.010407,655560.0,0.921524
40,S042_unit_43,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2425.253302,916.130576,1289.894830,646920.0,1081080.0,434160.0,185728.453912,338147.985146,235323.664566,645840.0,0.921501
47,S049_unit_49,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:06:00+00:00,2425.190497,916.364076,1289.795832,648000.0,1081080.0,433080.0,184774.196610,337192.329869,234368.098829,646920.0,0.921477
8,S008_unit_18,2023-02-17T07:48:00+00:00,2023-02-24T21:18:00+00:00,2023-03-01T21:54:00+00:00,2425.033168,928.879335,1289.342830,653400.0,1087560.0,434160.0,185359.050563,337749.991486,235095.149948,652320.0,0.921418
16,S017_unit_7,2023-02-17T07:48:00+00:00,2023-02-24T20:06:00+00:00,2023-03-01T20:42:00+00:00,2424.942598,918.417386,1289.347049,649080.0,1083240.0,434160.0,184825.480087,337218.934972,234455.728142,648000.0,0.921383
48,S050_unit_31,2023-02-17T07:48:00+00:00,2023-02-24T17:42:00+00:00,2023-03-01T18:18:00+00:00,2424.569856,907.533733,1288.804394,640440.0,1074600.0,434160.0,185379.978530,337749.333726,234979.799190,639360.0,0.921242
34,S036_unit_21,2023-02-17T07:48:00+00:00,2023-02-24T21:54:00+00:00,2023-03-01T22:30:00+00:00,2424.558870,934.128921,1288.673543,655560.0,1089720.0,434160.0,185311.056825,337669.925318,234990.140502,654480.0,0.921237
7,S007_unit_24,2023-02-17T07:48:00+00:00,2023-02-24T18:54:00+00:00,2023-03-01T19:30:00+00:00,2424.533245,912.435869,1288.807495,644760.0,1078920.0,434160.0,185408.386785,337777.993381,234964.664540,643680.0,0.921228
19,S020_unit_27,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2424.421645,915.868316,1288.564279,646920.0,1081080.0,434160.0,185499.846227,337853.643177,235102.855368,645840.0,0.921185
21,S023_unit_11,2023-02-17T07:48:00+00:00,2023-02-24T21:00:00+00:00,2023-03-01T21:36:00+00:00,2424.343066,926.492192,1288.422802,652320.0,1086480.0,434160.0,185516.951388,337861.163578,235131.330731,651240.0,0.921155
17,S018_unit_3,2023-02-17T07:48:00+00:00,2023-02-24T20:42:00+00:00,2023-03-01T21:18:00+00:00,2424.318974,924.363527,1288.410829,651240.0,1085400.0,434160.0,185672.751875,338010.323730,235266.154813,650160.0,0.921146
36,S038_unit_22,2023-02-17T07:48:00+00:00,2023-02-24T22:48:00+00:00,2023-03-01T23:24:00+00:00,2424.287391,942.386058,1288.217971,658800.0,1092960.0,434160.0,184970.692525,337303.417643,234663.618812,657720.0,0.921134
46,S048_unit_15,2023-02-17T07:48:00+00:00,2023-02-24T21:36:00+00:00,2023-03-01T22:12:00+00:00,2424.283477,931.656943,1288.382631,654480.0,1088640.0,434160.0,185574.251407,337908.645653,235145.608362,653400.0,0.921133
26,S028_unit_41,2023-02-17T07:48:00+00:00,2023-02-24T20:42:00+00:00,2023-03-01T21:00:00+00:00,2424.279255,922.469277,1288.337522,651240.0,1084320.0,433080.0,184750.730934,337088.978460,234352.169098,650160.0,0.921131

In [524]:
def load_state_hydrograph(state_id: str) -> pd.DataFrame:
    row = run_registry.loc[run_registry["state_id"].eq(state_id)].iloc[0]
    hydro = pd.read_csv(row["outlet_hydrograph_csv"])
    hydro["time_utc"] = pd.to_datetime(hydro["time_utc"], utc=True)
    return hydro

state_id = run_registry.loc[run_registry["status"].eq("ran"), "state_id"].iloc[0]
hydro = load_state_hydrograph(state_id)
hydro.head()

   time_seconds                  time_utc   q_outlet_cms  q_inflow_cms
0           0.0 2023-02-01 00:00:00+00:00  1.475375e-247      1381.345
1        1080.0 2023-02-01 00:18:00+00:00  1.270658e-244      1384.480
2        2160.0 2023-02-01 00:36:00+00:00  5.456054e-242      1390.750
3        3240.0 2023-02-01 00:54:00+00:00  1.557379e-239      1390.750
4        4320.0 2023-02-01 01:12:00+00:00  3.324540e-237      1397.040

In [525]:
row = run_registry.loc[run_registry["state_id"].eq(state_id)].iloc[0]
fig = go.Figure()
fig.add_trace(go.Scatter(x=hydro["time_utc"], y=hydro["q_inflow_cms"], mode="lines", name="Inflow"))
fig.add_trace(go.Scatter(x=hydro["time_utc"], y=hydro["q_outlet_cms"], mode="lines", name="Outlet"))
fig.add_vline(x=pd.to_datetime(row["event_start_time_utc"], utc=True), line_dash="dash", line_color="gray")
fig.add_vline(x=pd.to_datetime(row["peak_time_utc"], utc=True), line_dash="dot", line_color="red")
fig.update_layout(title=f"{state_id} outlet hydrograph", xaxis_title="time", yaxis_title="discharge (cms)")
fig.show()

In [526]:
summary = run_registry.copy()
for column in [
    "time_to_peak_seconds",
    "fall_time_seconds",
    "fall_time_50_seconds",
    "fall_time_10_seconds",
    "e_folding_time_seconds",
    "lag_to_inflow_peak_seconds",
]:
    summary[column.replace("_seconds", "_hours")] = pd.to_numeric(summary[column], errors="coerce") / 3600.0

px.scatter(
    summary,
    x="time_to_peak_hours",
    y="peak_discharge_cms",
    hover_name="state_id",
    color="peak_attenuation_ratio",
    title="Peak magnitude vs. time to peak",
)

## Merge RAPID outputs with base network metrics

For `independent-units`, each child state corresponds to one collapsed base unit. The merge below combines:

- `rapid_run_registry.csv`
- `transition_registry.csv`
- base `collapse_ranking.csv`

so you can compare outlet hydrograph behavior against the original unit metrics such as `equivalent_length`, `elongation`, and `topologic_complexity_score`.

In [527]:
transition_registry = pd.read_csv(experiment_dir / "transition_registry.csv")
base_collapse_ranking = pd.read_csv(experiment_dir / "states" / "S000_base" / "hierarchy" / "collapse_ranking.csv")

def parse_single_unit_id(value):
    if pd.isna(value):
        return pd.NA
    parts = [part.strip() for part in str(value).split(",") if part.strip()]
    if len(parts) != 1:
        return pd.NA
    return int(parts[0])

transition_registry["unit_id"] = transition_registry["selected_unit_ids"].apply(parse_single_unit_id).astype("Int64")
base_collapse_ranking["unit_id"] = pd.to_numeric(base_collapse_ranking["unit_id"], errors="coerce").astype("Int64")

analysis = summary.merge(
    transition_registry[["child_state_id", "unit_id", "collapsed_selection_label", "selected_collapse_order", "selected_collapse_priority_score"]],
    left_on="state_id",
    right_on="child_state_id",
    how="left",
)
analysis = analysis.merge(
    base_collapse_ranking,
    on="unit_id",
    how="left",
    suffixes=("", "_network"),
)

analysis["unit_id"] = analysis["unit_id"].astype("Int64")
analysis.head()

,state_id,rapid_prep_dir,rapid_run_dir,qout_nc,status,hydrograph_status,outlet_hydrograph_csv,hydrograph_metrics_csv,hydrograph_metrics_json,event_definition_version,...,unit_node_ids,unit_node_count,unit_topodynamic_class,path_disparity_width_rank_component,elongation_rank_component,equivalent_length_rank_component,topologic_complexity_score_rank_component,collapse_priority_score,collapse_order_global,collapse_order_in_bubble
0,S000_base,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S001_unit_28,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"55,56",2.0,dominant_simple_split,1.000000,1.000000,1.000000,0.892157,0.973039,1.0,1.0
2,S002_unit_33,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"62,63",2.0,dominant_simple_split,0.960784,0.921569,0.901961,0.892157,0.919118,2.0,1.0
3,S003_unit_29,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"57,58",2.0,dominant_simple_split,0.764706,0.882353,0.803922,0.892157,0.835784,3.0,1.0
4,S004_unit_2,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"5,7",2.0,dominant_simple_split,0.803922,0.823529,0.745098,0.892157,0.816176,4.0,1.0

In [528]:
comparison_cols = [
    "state_id",
    "unit_id",
    "collapsed_selection_label",
    "peak_discharge_cms",
    "peak_excess_cms",
    "time_to_peak_hours",
    "peak_attenuation_ratio",
    "equivalent_length",
    "elongation",
    "effective_n_paths_width",
    "path_disparity_width",
    "topologic_complexity_score",
    "collapse_priority_score",
    "collapse_order_global",
]
analysis[comparison_cols].sort_values("peak_discharge_cms", ascending=False)

,state_id,unit_id,collapsed_selection_label,peak_discharge_cms,peak_excess_cms,time_to_peak_hours,peak_attenuation_ratio,equivalent_length,elongation,effective_n_paths_width,path_disparity_width,topologic_complexity_score,collapse_priority_score,collapse_order_global
44,S046_unit_10,10,collapsed_unit_10,2431.794794,912.728429,179.4,0.923987,1527.503259,9.868908,1.949146,1.026090,2.197225,0.200980,46.0
50,S052_unit_46,46,collapsed_unit_46,2430.016884,911.187722,179.1,0.923311,1256.626569,7.071783,1.964709,1.017962,3.295837,0.085784,52.0
33,S035_unit_1,1,collapsed_unit_1,2429.512896,916.476336,180.0,0.923120,640.685510,2.737434,1.792455,1.115788,2.484907,0.372549,35.0
49,S051_unit_51,51,collapsed_unit_51,2429.223832,907.670393,178.2,0.923010,1812.440210,3.299438,2.949330,1.017180,2.772589,0.129902,51.0
43,S045_unit_47,47,collapsed_unit_47,2427.559255,917.300255,180.0,0.922378,676.002616,5.748915,1.997811,1.001096,1.791759,0.237745,45.0
32,S034_unit_26,26,collapsed_unit_26,2427.301392,907.494179,177.9,0.922280,969.350112,1.371095,2.622645,1.143883,2.772589,0.404412,34.0
39,S041_unit_20,20,collapsed_unit_20,2427.108957,914.958408,179.7,0.922206,1682.185633,3.508595,2.334495,1.285074,3.178054,0.306373,41.0
4,S004_unit_2,2,collapsed_unit_2,2426.954081,912.166395,179.1,0.922148,395.415364,0.809090,1.670688,1.197112,1.098612,0.816176,4.0
41,S043_unit_12,12,collapsed_unit_12,2426.592603,913.728174,179.4,0.922010,1338.397639,2.126452,2.747257,1.091998,3.178054,0.281863,43.0
1,S001_unit_28,28,collapsed_unit_28,2426.516309,913.511319,179.4,0.921981,158.994781,0.285108,1.435446,1.393295,1.098612,0.973039,1.0
24,S026_unit_4,4,collapsed_unit_4,2425.831976,914.009416,179.4,0.921721,1025.358480,2.506279,1.604086,1.246816,1.791759,0.468137,26.0
3,S003_unit_29,29,collapsed_unit_29,2425.483838,915.677012,179.7,0.921589,330.916236,0.773831,1.685291,1.186738,1.098612,0.835784,3.0
9,S009_unit_25,25,collapsed_unit_25,2425.481613,910.998606,178.8,0.921588,529.726733,1.113518,1.455079,1.374496,1.098612,0.727941,9.0
13,S013_unit_14,14,collapsed_unit_14,2425.397330,917.924052,180.0,0.921556,207.962672,1.058474,1.853643,1.078957,1.791759,0.688725,13.0
45,S047_unit_48,48,collapsed_unit_48,2425.313078,935.886629,182.4,0.921524,673.056409,1.685030,2.953125,1.015873,3.871201,0.200980,47.0
40,S042_unit_43,43,collapsed_unit_43,2425.253302,916.130576,179.7,0.921501,548.083856,1.426138,1.963906,1.018378,2.890372,0.306373,42.0
47,S049_unit_49,49,collapsed_unit_49,2425.190497,916.364076,180.0,0.921477,843.379735,4.353087,1.999366,1.000317,2.484907,0.161765,49.0
8,S008_unit_18,18,collapsed_unit_18,2425.033168,928.879335,181.5,0.921418,397.881749,0.937630,1.582174,1.264084,1.791759,0.737745,8.0
16,S017_unit_7,7,collapsed_unit_7,2424.942598,918.417386,180.3,0.921383,460.582597,0.990106,1.677872,1.191986,1.791759,0.659314,17.0
48,S050_unit_31,31,collapsed_unit_31,2424.569856,907.533733,177.9,0.921242,2575.495446,2.403253,5.755322,1.042513,5.164786,0.156863,50.0
34,S036_unit_21,21,collapsed_unit_21,2424.558870,934.128921,182.1,0.921237,1481.279278,3.546323,1.826999,1.094691,1.791759,0.370098,36.0
7,S007_unit_24,24,collapsed_unit_24,2424.533245,912.435869,179.1,0.921228,316.469059,0.682400,1.950113,1.025582,1.098612,0.737745,7.0
19,S020_unit_27,27,collapsed_unit_27,2424.421645,915.868316,179.7,0.921185,425.469114,1.265245,1.909113,1.047607,1.098612,0.610294,20.0
21,S023_unit_11,11,collapsed_unit_11,2424.343066,926.492192,181.2,0.921155,585.464558,1.252030,1.611562,1.241032,2.197225,0.544118,23.0
17,S018_unit_3,3,collapsed_unit_3,2424.318974,924.363527,180.9,0.921146,277.647939,0.776090,1.958632,1.021121,1.791759,0.649510,18.0
36,S038_unit_22,22,collapsed_unit_22,2424.287391,942.386058,183.0,0.921134,894.648558,4.365288,1.866092,1.071759,1.791759,0.360294,38.0
46,S048_unit_15,15,collapsed_unit_15,2424.283477,931.656943,181.8,0.921133,1253.322715,4.405827,1.884575,1.061247,3.295837,0.178922,48.0
26,S028_unit_41,41,collapsed_unit_41,2424.279255,922.469277,180.9,0.921131,713.886368,1.371692,1.877796,1.065078,1.791759,0.448529,28.0
5,S005_unit_16,16,collapsed_unit_16,2424.013769,918.708232,180.3,0.921030,396.973590,0.994603,1.654712,1.208670,1.098612,0.772059,5.0
35,S037_unit_30,30,collapsed_unit_30,2424.008400,922.348469,180.9,0.921028,1207.955322,4.737181,1.942417,1.029645,1.098612,0.365196,37.0
6,S006_unit_23,23,collapsed_unit_23,2423.892949,924.768278,181.2,0.920984,197.296010,1.473757,1.790224,1.117179,1.098612,0.747549,6.0
30,S032_unit_35,35,collapsed_unit_35,2423.889438,923.043947,180.9,0.920983,591.148748,2.229047,1.964267,1.018192,1.098612,0.424020,32.0
22,S024_unit_8,8,collapsed_unit_8,2423.833283,925.218439,181.2,0.920962,629.180384,2.230468,1.596784,1.252517,1.791759,0.522059,24.0
27,S029_unit_36,36,collapsed_unit_36,2423.752826,925.003925,181.2,0.920931,452.841139,1.023979,1.954406,1.023329,2.484907,0.446078,29.0
2,S002_unit_33,33,collapsed_unit_33,2423.710535,920.701908,180.6,0.920915,257.726247,0.656442,1.528138,1.308783,1.098612,0.919118,2.0
20,S021_unit_38,38,collapsed_unit_38,2423.699958,923.722455,180.9,0.920911,322.023586,0.640306,1.950349,1.025458,2.484907,0.588235,21.0
10,S010_unit_34,34,collapsed_unit_34,2423.689011,922.859891,180.9,0.920907,232.686563,0.787713,1.858455,1.076163,1.791759,0.727941,10.0
18,S019_unit_42,42,collapsed_unit_42,2423.657683,925.137945,181.2,0.920895,417.534129,0.973634,1.884468,1.061307,1.791759,0.610294,19.0
0,S000_base,<NA>,NaN,2423.624516,924.552291,180.9,0.920882,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,S012_unit_40,40,collapsed_unit_40,2423.613207,923.829754,180.9,0.920878,381.918257,0.874464,1.801465,1.110208,1.791759,0.708333,12.0
15,S016_unit_37,37,collapsed_unit_37,2423.609339,921.792833,180.6,0.920877,312.584405,0.635292,1.854256,1.078600,2.484907,0.666667,16.0
31,S033_unit_50,50,collapsed_unit_50,2423.596366,920.635335,180.6,0.920872,573.886320,1.896217,1.877557,1.065214,2.197225,0.416667,33.0
11,S011_unit_6,6,collapsed_unit_6,2423.371698,922.375133,180.9,0.920786,353.810273,0.931900,1.760964,1.135741,1.791759,0.718137,11.0
38,S040_unit_32,32,collapsed_unit_32,2422.926419,922.428728,180.9,0.920617,588.806299,1.078162,2.884042,1.040207,3.465736,0.343137,40.0
28,S030_unit_39,39,collapsed_unit_39,2422.889201,929.472338,181.5,0.920603,455.337722,0.859529,1.991886,1.004074,2.484907,0.431373,30.0
14,S015_unit_17,17,collapsed_unit_17,2422.485921,927.118517,181.2,0.920450,230.340202,0.565348,1.962218,1.019255,1.791759,0.683824,15.0
29,S031_unit_45,45,collapsed_unit_45,2422.301855,921.379704,180.6,0.920380,491.612529,1.883619,1.959826,1.020499,1.791759,0.428922,31.0
37,S039_unit_9,9,collapsed_unit_9,2421.368802,933.803251,182.1,0.920025,511.113471,0.966404,1.981531,1.009321,2.890372,0.360294,39.0
42,S044_unit_19,19,collapsed_unit_19,2420.740558,926.712950,181.2,0.919787,605.920553,2.149522,1.953158,1.023983,2.890372,0.274510,44.0
23,S025_unit_44,44,collapsed_unit_44,2420.493461,936.295431,182.4,0.919693,553.946472,1.221216,1.829815,1.093007,2.484907,0.475490,25.0
25,S027_unit_52,52,collapsed_unit_52,2420.082978,990.136084,186.6,0.919537,460.783203,1.809386,1.983741,1.008196,1.098612,0.468137,27.0

In [529]:
network_metric_columns = [
    "equivalent_length",
    "elongation",
    "effective_n_paths_width",
    "path_disparity_width",
    "topologic_complexity_score",
    "collapse_priority_score",
]

plot_df = analysis.loc[analysis["unit_id"].notna()].copy()
plot_df["unit_id"] = plot_df["unit_id"].astype(int)
plot_df["state_label"] = plot_df["state_id"] + " | unit " + plot_df["unit_id"].astype(str)

network_vs_peak = plot_df.melt(
    id_vars=["state_id", "state_label", "unit_id", "peak_discharge_cms", "peak_attenuation_ratio", "time_to_peak_hours"],
    value_vars=network_metric_columns,
    var_name="network_metric",
    value_name="network_value",
).dropna(subset=["network_value"])

px.scatter(
    network_vs_peak,
    x="network_value",
    y="peak_discharge_cms",
    facet_col="network_metric",
    facet_col_wrap=3,
    hover_name="state_label",
    color="peak_attenuation_ratio",
    title="Peak discharge vs. selected network metrics",
)

In [530]:
corr_columns = [
    "peak_discharge_cms",
    "peak_excess_cms",
    "time_to_peak_hours",
    "fall_time_50_hours",
    "peak_attenuation_ratio",
    "equivalent_length",
    "elongation",
    "effective_n_paths_width",
    "path_disparity_width",
    "topologic_complexity_score",
    "collapse_priority_score",
]

corr_df = analysis.loc[analysis["unit_id"].notna(), corr_columns].apply(pd.to_numeric, errors="coerce")
corr = corr_df.corr(numeric_only=True)

px.imshow(
    corr,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Correlation between RAPID hydrograph metrics and network metrics",
)

## Expanded network predictors and bubble-membership analysis

This second analysis block keeps the original heatmap above, but broadens the network side with additional width and topology metrics and swaps the RAPID side to focus on:

- `time_to_peak_hours`
- `fall_time_10_hours`
- `peak_attenuation_ratio`
- `lag_to_inflow_peak_hours`
- `outlet_excess_volume_m3`
- `rise_rate_cms_per_hour`

It also adds a separate look at `time_to_peak` vs bubble membership.

In [531]:
analysis = analysis.copy()
analysis["lag_to_inflow_peak_hours"] = pd.to_numeric(analysis["lag_to_inflow_peak_seconds"], errors="coerce") / 3600.0
analysis["bubble_membership"] = analysis["in_compound_bubble"].map({True: "bubble_member", False: "standalone"}).fillna("unknown")

rapid_metric_columns_expanded = [
    "time_to_peak_hours",
    "fall_time_10_hours",
]

network_metric_candidates_expanded = [
    "bifurcation",
    "confluence",
    "equivalent_width",
    "equivalent_length",
    "n_paths",
    "n_valid_paths",
    "elongation",
    "path_length_min",
    "path_length_max",
    "path_length_mean",
    # "path_length_range",
    "path_length_range_norm",
    "path_length_cv",
    "path_width_eq_min",
    # "path_width_eq_max",
    "path_width_eq_mean",
    "path_width_range",
    "path_width_range_norm",
    "largest_path_width_fraction",
    "dominant_width_fraction",
    "width_entropy",
    "width_evenness",
    "effective_n_paths_width",
    "path_disparity_width",
    "width_ratio_2",
    "smaller_width_fraction_2",
    "dominant_width_fraction_2",
    "length_ratio_2",
    "internal_bifurcation_count",
    # "internal_confluence_count",
    "total_bifurcation_count",
    # "total_confluence_count",
    "internal_branch_node_count",
    "branching_density_by_length",
    "path_redundancy",
    "compound_indicator",
    # "topologic_complexity_score",
    "dynamic_proxy_entropy",
    "effective_n_paths_dyn_width",
    "dominant_dyn_fraction_width",
    "dynamic_proxy_complexity_score",
    "unit_node_count",
    "depth_from_root",
    "collapse_level",
    "n_children",
    "n_descendants",
    # "path_disparity_width_rank_component",
    # "elongation_rank_component",
    # "equivalent_length_rank_component",
    # "topologic_complexity_score_rank_component",
    "collapse_priority_score",
]

available_network_metrics_expanded = [
    column for column in network_metric_candidates_expanded if column in analysis.columns
]

available_network_metrics_expanded

['bifurcation',
 'confluence',
 'equivalent_width',
 'equivalent_length',
 'n_paths',
 'n_valid_paths',
 'elongation',
 'path_length_min',
 'path_length_max',
 'path_length_mean',
 'path_length_range_norm',
 'path_length_cv',
 'path_width_eq_min',
 'path_width_eq_mean',
 'path_width_range',
 'path_width_range_norm',
 'largest_path_width_fraction',
 'dominant_width_fraction',
 'width_entropy',
 'width_evenness',
 'effective_n_paths_width',
 'path_disparity_width',
 'width_ratio_2',
 'smaller_width_fraction_2',
 'dominant_width_fraction_2',
 'length_ratio_2',
 'internal_bifurcation_count',
 'total_bifurcation_count',
 'internal_branch_node_count',
 'branching_density_by_length',
 'path_redundancy',
 'compound_indicator',
 'dynamic_proxy_entropy',
 'effective_n_paths_dyn_width',
 'dominant_dyn_fraction_width',
 'dynamic_proxy_complexity_score',
 'unit_node_count',
 'depth_from_root',
 'collapse_level',
 'n_children',
 'n_descendants',
 'collapse_priority_score']

In [532]:
corr_columns_expanded = rapid_metric_columns_expanded + available_network_metrics_expanded
corr_df_expanded = analysis.loc[analysis["unit_id"].notna(), corr_columns_expanded].apply(pd.to_numeric, errors="coerce")
corr_expanded = corr_df_expanded.corr(numeric_only=True)
cross_corr = corr_expanded.loc[rapid_metric_columns_expanded, available_network_metrics_expanded]

fig = px.imshow(
    cross_corr,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Cross-domain correlations: time to peak and fall time vs. network metrics",
)
fig.update_xaxes(title="Network metrics")
fig.update_yaxes(title="RAPID metrics")
fig

In [ ]:
- equivalent length
- elongation
-

In [533]:
cross_domain_rows = []
for rapid_metric in rapid_metric_columns_expanded:
    for network_metric in available_network_metrics_expanded:
        corr_value = cross_corr.loc[rapid_metric, network_metric]
        cross_domain_rows.append(
            {
                "rapid_metric": rapid_metric,
                "network_metric": network_metric,
                "correlation": corr_value,
                "abs_correlation": abs(corr_value),
            }
        )

cross_domain_corr = pd.DataFrame(cross_domain_rows).sort_values("abs_correlation", ascending=False)
cross_domain_corr.head(20)

,rapid_metric,network_metric,correlation,abs_correlation
39,time_to_peak_hours,n_children,-0.357783,0.357783
40,time_to_peak_hours,n_descendants,-0.357783,0.357783
8,time_to_peak_hours,path_length_max,-0.354369,0.354369
4,time_to_peak_hours,n_paths,-0.352723,0.352723
5,time_to_peak_hours,n_valid_paths,-0.352723,0.352723
30,time_to_peak_hours,path_redundancy,-0.352723,0.352723
2,time_to_peak_hours,equivalent_width,-0.346004,0.346004
79,fall_time_10_hours,depth_from_root,-0.343862,0.343862
9,time_to_peak_hours,path_length_mean,-0.342467,0.342467
3,time_to_peak_hours,equivalent_length,-0.319674,0.319674
7,time_to_peak_hours,path_length_min,-0.316394,0.316394
38,time_to_peak_hours,collapse_level,-0.314366,0.314366
31,time_to_peak_hours,compound_indicator,-0.314366,0.314366
14,time_to_peak_hours,path_width_range,-0.298508,0.298508
33,time_to_peak_hours,effective_n_paths_dyn_width,-0.272852,0.272852
20,time_to_peak_hours,effective_n_paths_width,-0.272852,0.272852
42,fall_time_10_hours,bifurcation,-0.249364,0.249364
43,fall_time_10_hours,confluence,-0.248382,0.248382
24,time_to_peak_hours,dominant_width_fraction_2,-0.238945,0.238945
23,time_to_peak_hours,smaller_width_fraction_2,0.238945,0.238945

In [534]:
px.bar(
    cross_domain_corr.head(15),
    x="abs_correlation",
    y="network_metric",
    color="rapid_metric",
    orientation="h",
    hover_data=["correlation"],
    title="Strongest RAPID vs. network correlations",
)

In [535]:
bubble_df = analysis.loc[analysis["unit_id"].notna()].copy()
bubble_df["unit_id"] = bubble_df["unit_id"].astype(int)
bubble_df["state_label"] = bubble_df["state_id"] + " | unit " + bubble_df["unit_id"].astype(str)

px.box(
    bubble_df,
    x="bubble_membership",
    y="time_to_peak_hours",
    color="bubble_membership",
    points="all",
    hover_name="state_label",
    title="Time to peak by bubble membership",
)

In [536]:
px.box(
    bubble_df,
    x="bubble_membership",
    y="fall_time_10_hours",
    color="bubble_membership",
    points="all",
    hover_name="state_label",
    title="Fall time 10 by bubble membership",
)