# RAPID Hydrograph Peak selection

In [449]:
p1 = stat1.copy()
p2 = stat2.copy()
# p3 = stat3.copy()
# p4 = stat4.copy()


# tstart = '2024-10-13 00:01:00+0000'
# tend   = '2025-10-22 00:00:00+0000'
# p1 = p1[(p1['time'] > tstart) & (p1['time'] < tend)]
# p2 = p2[(p2['time'] > tstart) & (p2['time'] < tend)]
# p3 = p3[(p3['time'] > tstart) & (p3['time'] < tend)]
# p4 = p4[(p4['time'] > tstart) & (p4['time'] < tend)]

stationList = [p1,p2]
# stationList = [p1,p2, p3, p4]

In [457]:
np.sqrt(2)

np.float64(1.4142135623730951)

In [450]:
fig = go.Figure()
for p in stationList:
    fig.add_trace(go.Scatter(
        x=p["time"],
        y=p["discharge"],
        mode="markers",
        name=p['station_key'].iloc[0],
        hovertemplate=f"{p['station_key'].iloc[0]}" +"<br>time: %{x}<br>discharge: %{y}<extra></extra>"
    ))

# fig.add_trace(go.Scatter(
#     x=p2["time"],
#     y=p2["discharge"],
#     mode="markers",
#     name=f"{p2['station_key'].iloc[0]}",
#     hovertemplate=f"{p2['station_key'].iloc[0]}"+"<br>time: %{x}<br>discharge: %{y}<extra></extra>"
# ))

fig.update_layout(
    title="Discharge over Time",
    xaxis_title="time",
    yaxis_title="discharge"
)

fig.show('browser')

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

# RAPID Analysis

In [1]:
import sys
from pathlib import Path

ROOT = Path("/Users/6256481/Code/river-hierarchy")
RAPID_SRC = ROOT / "RAPID" / "src"

if str(RAPID_SRC) not in sys.path:
    sys.path.insert(0, str(RAPID_SRC))

In [9]:
from pathlib import Path

from rapid_tools.analysis import (
    build_combined_analysis_frame,
    plot_effect_signature,
    plot_hydrograph_overlay,
    write_wave_gif,
)

indep_dir = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/03_indep__anchored")
compound_dir = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/03_compound_bubbles__anchored")

analysis = build_combined_analysis_frame(indep_dir, compound_dir)

fig = plot_effect_signature(analysis)
fig.show()

fig2 = plot_hydrograph_overlay(indep_dir)
fig2.show()

TypeError: plot_hydrograph_overlay() missing 1 required positional argument: 'state_ids'

In [12]:
import importlib
import rapid_tools.analysis
importlib.reload(rapid_tools.analysis)

In [31]:
import importlib
import rapid_tools.analysis
importlib.reload(rapid_tools.analysis)

from rapid_tools.analysis import (
    build_matched_corridor_hydrograph_frame,
    plot_matched_corridor_hydrographs,
)

hydro = build_matched_corridor_hydrograph_frame(
    indep_dir,
    "S046_unit_10",
    reference_state_id="S000_base",
    n_upstream=5,
    n_downstream=10,
    use_event_window=True,
)

fig = plot_matched_corridor_hydrographs(
    hydro,
    title="S046_unit_10: matched upstream/downstream parent-link hydrographs",
)
fig.show('browser')

In [25]:
from rapid_tools.analysis import (
    build_matched_corridor_hydrograph_frame,
    plot_matched_corridor_hydrographs,
    summarize_matched_corridor_peak_timing,
)

hydro = build_matched_corridor_hydrograph_frame(
    indep_dir,
    "S046_unit_10",
    reference_state_id="S000_base",
    n_upstream=5,
    n_downstream=5,
    use_event_window=True,
)

peak_summary = summarize_matched_corridor_peak_timing(hydro)
peak_summary

,corridor_side,corridor_order,panel_label,parent_link_id,graph_distance,reference_peak_time_seconds,reference_peak_time_hours,reference_peak_q_cms,variant_peak_time_seconds,variant_peak_time_hours,variant_peak_q_cms,delta_peak_time_hours,delta_peak_q_cms
0,downstream,1,D1 | parent 5,5,2,1630800.0,453.0,2508.539933,1626480.0,451.8,2520.980754,-1.2,12.440821
1,downstream,2,D2 | parent 11,11,3,1652400.0,459.0,2467.872366,1647000.0,457.5,2478.101286,-1.5,10.228920
2,downstream,3,D3 | parent 19,19,3,1645920.0,457.2,2488.031299,1641600.0,456.0,2496.772884,-1.2,8.741586
3,downstream,4,D4 | parent 12,12,4,1658880.0,460.8,2442.284705,1653480.0,459.3,2450.284608,-1.5,7.999903
4,downstream,5,D5 | parent 15,15,4,1657800.0,460.5,2446.881968,1653480.0,459.3,2450.284608,-1.2,3.402640
5,upstream,1,U1 | parent 28,28,1,1574640.0,437.4,2305.981372,1577880.0,438.3,2359.999736,0.9,54.018364
6,upstream,2,U2 | parent 35,35,2,1553040.0,431.4,2175.450551,1553040.0,431.4,2215.241515,0.0,39.790964
7,upstream,3,U3 | parent 34,34,2,1551960.0,431.1,2168.464968,1551960.0,431.1,2208.198238,0.0,39.733270
8,upstream,4,U4 | parent 37,37,3,1530360.0,425.1,2028.807149,1530360.0,425.1,2064.070839,0.0,35.263690
9,upstream,5,U5 | parent 45,45,4,1541160.0,428.1,2097.873714,1541160.0,428.1,2136.000001,0.0,38.126287

In [26]:
fig = plot_matched_corridor_hydrographs(
    hydro,
    title="S046_unit_10: matched upstream/downstream parent-link hydrographs",
    show_peak_markers=True,
)
fig.show()

# RAPID Hydrograph Analysis

Use this notebook after `RAPID/run_rapid_experiment.py` has finished. It reads the per-state outlet hydrographs and hydrograph metrics written under each state's `rapid/run/` folder.

In [493]:
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [522]:
experiment_dir = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/03_indep")
run_registry = pd.read_csv(experiment_dir / "rapid_run_registry.csv")
run_registry.head()

,state_id,rapid_prep_dir,rapid_run_dir,qout_nc,status,hydrograph_status,outlet_hydrograph_csv,hydrograph_metrics_csv,hydrograph_metrics_json,event_definition_version,...,outlet_excess_volume_m3,outlet_reach_count,outlet_reach_ids,hydrograph_duration_seconds,metric_config,fall_time_seconds,fall_time_50_seconds,fall_time_10_seconds,e_folding_time_seconds,rise_rate_cms_per_hour
0,S000_base,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.457795e+08,1,[746],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185724.429126,338007.859584,235304.585060,5.110847
1,S001_unit_28,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.357741e+08,1,[738],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185120.528941,337647.363379,234814.308777,5.092036
2,S002_unit_33,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.427600e+08,1,[741],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",433080.0,184945.450130,337239.407698,234511.510665,5.098017
3,S003_unit_29,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.379520e+08,1,[738],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185410.187725,337852.155781,235055.076056,5.095587
4,S004_unit_2,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,2.345530e+08,1,[737],3196800.0,"{""start_mode"": ""auto_local_min"", ""end_mode"": ""...",434160.0,185268.660461,337829.628672,234980.659188,5.093056

In [523]:
metric_cols = [
    "state_id",
    "event_start_time_utc",
    "peak_time_utc",
    "event_end_time_utc",
    "peak_discharge_cms",
    "peak_excess_cms",
    "peak_excess_to_end_baseline_cms",
    "time_to_peak_seconds",
    "event_duration_seconds",
    "fall_time_seconds",
    "fall_time_50_seconds",
    "fall_time_10_seconds",
    "e_folding_time_seconds",
    "lag_to_inflow_peak_seconds",
    "peak_attenuation_ratio",
]
run_registry[metric_cols].sort_values("peak_discharge_cms", ascending=False).head(28)

,state_id,event_start_time_utc,peak_time_utc,event_end_time_utc,peak_discharge_cms,peak_excess_cms,peak_excess_to_end_baseline_cms,time_to_peak_seconds,event_duration_seconds,fall_time_seconds,fall_time_50_seconds,fall_time_10_seconds,e_folding_time_seconds,lag_to_inflow_peak_seconds,peak_attenuation_ratio
44,S046_unit_10,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T20:06:00+00:00,2431.794794,912.728429,1299.364835,645840.0,1081080.0,435240.0,184606.284349,337547.869158,234884.436435,644760.0,0.923987
50,S052_unit_46,2023-02-17T07:48:00+00:00,2023-02-24T18:54:00+00:00,2023-03-01T19:30:00+00:00,2430.016884,911.187722,1297.134010,644760.0,1078920.0,434160.0,184701.469838,337502.843113,234539.533240,643680.0,0.923311
33,S035_unit_1,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:42:00+00:00,2429.512896,916.476336,1295.995996,648000.0,1083240.0,435240.0,184738.211666,337492.366218,234811.578278,646920.0,0.923120
49,S051_unit_51,2023-02-17T07:48:00+00:00,2023-02-24T18:00:00+00:00,2023-03-01T18:36:00+00:00,2429.223832,907.670393,1295.982765,641520.0,1075680.0,434160.0,184650.248823,337399.570562,234413.985386,640440.0,0.923010
43,S045_unit_47,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:42:00+00:00,2427.559255,917.300255,1293.329195,648000.0,1083240.0,435240.0,185356.077945,337955.068841,235111.896711,646920.0,0.922378
32,S034_unit_26,2023-02-17T07:48:00+00:00,2023-02-24T17:42:00+00:00,2023-03-01T18:36:00+00:00,2427.301392,907.494179,1292.967219,640440.0,1075680.0,435240.0,185430.916969,338020.014670,235155.464830,639360.0,0.922280
39,S041_unit_20,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2427.108957,914.958408,1292.571148,646920.0,1081080.0,434160.0,184974.925874,337539.676476,234762.460996,645840.0,0.922206
4,S004_unit_2,2023-02-17T07:48:00+00:00,2023-02-24T18:54:00+00:00,2023-03-01T19:30:00+00:00,2426.954081,912.166395,1292.434312,644760.0,1078920.0,434160.0,185268.660461,337829.628672,234980.659188,643680.0,0.922148
41,S043_unit_12,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T19:48:00+00:00,2426.592603,913.728174,1291.853763,645840.0,1080000.0,434160.0,185255.932711,337787.187889,234972.674676,644760.0,0.922010
1,S001_unit_28,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T19:48:00+00:00,2426.516309,913.511319,1291.765570,645840.0,1080000.0,434160.0,185120.528941,337647.363379,234814.308777,644760.0,0.921981
24,S026_unit_4,2023-02-17T07:48:00+00:00,2023-02-24T19:12:00+00:00,2023-03-01T19:48:00+00:00,2425.831976,914.009416,1290.700609,645840.0,1080000.0,434160.0,185427.557451,337895.709847,235104.191594,644760.0,0.921721
3,S003_unit_29,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2425.483838,915.677012,1290.192766,646920.0,1081080.0,434160.0,185410.187725,337852.155781,235055.076056,645840.0,0.921589
9,S009_unit_25,2023-02-17T07:48:00+00:00,2023-02-24T18:36:00+00:00,2023-03-01T19:12:00+00:00,2425.481613,910.998606,1290.182207,643680.0,1077840.0,434160.0,185400.929375,337842.939900,235050.969502,642600.0,0.921588
13,S013_unit_14,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:24:00+00:00,2425.397330,917.924052,1290.112589,648000.0,1082160.0,434160.0,185685.063013,338118.900507,235289.630260,646920.0,0.921556
45,S047_unit_48,2023-02-17T07:48:00+00:00,2023-02-24T22:12:00+00:00,2023-03-01T22:48:00+00:00,2425.313078,935.886629,1289.797327,656640.0,1090800.0,434160.0,184890.943265,337293.546087,234616.010407,655560.0,0.921524
40,S042_unit_43,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2425.253302,916.130576,1289.894830,646920.0,1081080.0,434160.0,185728.453912,338147.985146,235323.664566,645840.0,0.921501
47,S049_unit_49,2023-02-17T07:48:00+00:00,2023-02-24T19:48:00+00:00,2023-03-01T20:06:00+00:00,2425.190497,916.364076,1289.795832,648000.0,1081080.0,433080.0,184774.196610,337192.329869,234368.098829,646920.0,0.921477
8,S008_unit_18,2023-02-17T07:48:00+00:00,2023-02-24T21:18:00+00:00,2023-03-01T21:54:00+00:00,2425.033168,928.879335,1289.342830,653400.0,1087560.0,434160.0,185359.050563,337749.991486,235095.149948,652320.0,0.921418
16,S017_unit_7,2023-02-17T07:48:00+00:00,2023-02-24T20:06:00+00:00,2023-03-01T20:42:00+00:00,2424.942598,918.417386,1289.347049,649080.0,1083240.0,434160.0,184825.480087,337218.934972,234455.728142,648000.0,0.921383
48,S050_unit_31,2023-02-17T07:48:00+00:00,2023-02-24T17:42:00+00:00,2023-03-01T18:18:00+00:00,2424.569856,907.533733,1288.804394,640440.0,1074600.0,434160.0,185379.978530,337749.333726,234979.799190,639360.0,0.921242
34,S036_unit_21,2023-02-17T07:48:00+00:00,2023-02-24T21:54:00+00:00,2023-03-01T22:30:00+00:00,2424.558870,934.128921,1288.673543,655560.0,1089720.0,434160.0,185311.056825,337669.925318,234990.140502,654480.0,0.921237
7,S007_unit_24,2023-02-17T07:48:00+00:00,2023-02-24T18:54:00+00:00,2023-03-01T19:30:00+00:00,2424.533245,912.435869,1288.807495,644760.0,1078920.0,434160.0,185408.386785,337777.993381,234964.664540,643680.0,0.921228
19,S020_unit_27,2023-02-17T07:48:00+00:00,2023-02-24T19:30:00+00:00,2023-03-01T20:06:00+00:00,2424.421645,915.868316,1288.564279,646920.0,1081080.0,434160.0,185499.846227,337853.643177,235102.855368,645840.0,0.921185
21,S023_unit_11,2023-02-17T07:48:00+00:00,2023-02-24T21:00:00+00:00,2023-03-01T21:36:00+00:00,2424.343066,926.492192,1288.422802,652320.0,1086480.0,434160.0,185516.951388,337861.163578,235131.330731,651240.0,0.921155
17,S018_unit_3,2023-02-17T07:48:00+00:00,2023-02-24T20:42:00+00:00,2023-03-01T21:18:00+00:00,2424.318974,924.363527,1288.410829,651240.0,1085400.0,434160.0,185672.751875,338010.323730,235266.154813,650160.0,0.921146
36,S038_unit_22,2023-02-17T07:48:00+00:00,2023-02-24T22:48:00+00:00,2023-03-01T23:24:00+00:00,2424.287391,942.386058,1288.217971,658800.0,1092960.0,434160.0,184970.692525,337303.417643,234663.618812,657720.0,0.921134
46,S048_unit_15,2023-02-17T07:48:00+00:00,2023-02-24T21:36:00+00:00,2023-03-01T22:12:00+00:00,2424.283477,931.656943,1288.382631,654480.0,1088640.0,434160.0,185574.251407,337908.645653,235145.608362,653400.0,0.921133
26,S028_unit_41,2023-02-17T07:48:00+00:00,2023-02-24T20:42:00+00:00,2023-03-01T21:00:00+00:00,2424.279255,922.469277,1288.337522,651240.0,1084320.0,433080.0,184750.730934,337088.978460,234352.169098,650160.0,0.921131

In [524]:
def load_state_hydrograph(state_id: str) -> pd.DataFrame:
    row = run_registry.loc[run_registry["state_id"].eq(state_id)].iloc[0]
    hydro = pd.read_csv(row["outlet_hydrograph_csv"])
    hydro["time_utc"] = pd.to_datetime(hydro["time_utc"], utc=True)
    return hydro

state_id = run_registry.loc[run_registry["status"].eq("ran"), "state_id"].iloc[0]
hydro = load_state_hydrograph(state_id)
hydro.head()

   time_seconds                  time_utc   q_outlet_cms  q_inflow_cms
0           0.0 2023-02-01 00:00:00+00:00  1.475375e-247      1381.345
1        1080.0 2023-02-01 00:18:00+00:00  1.270658e-244      1384.480
2        2160.0 2023-02-01 00:36:00+00:00  5.456054e-242      1390.750
3        3240.0 2023-02-01 00:54:00+00:00  1.557379e-239      1390.750
4        4320.0 2023-02-01 01:12:00+00:00  3.324540e-237      1397.040

In [525]:
row = run_registry.loc[run_registry["state_id"].eq(state_id)].iloc[0]
fig = go.Figure()
fig.add_trace(go.Scatter(x=hydro["time_utc"], y=hydro["q_inflow_cms"], mode="lines", name="Inflow"))
fig.add_trace(go.Scatter(x=hydro["time_utc"], y=hydro["q_outlet_cms"], mode="lines", name="Outlet"))
fig.add_vline(x=pd.to_datetime(row["event_start_time_utc"], utc=True), line_dash="dash", line_color="gray")
fig.add_vline(x=pd.to_datetime(row["peak_time_utc"], utc=True), line_dash="dot", line_color="red")
fig.update_layout(title=f"{state_id} outlet hydrograph", xaxis_title="time", yaxis_title="discharge (cms)")
fig.show()

In [526]:
summary = run_registry.copy()
for column in [
    "time_to_peak_seconds",
    "fall_time_seconds",
    "fall_time_50_seconds",
    "fall_time_10_seconds",
    "e_folding_time_seconds",
    "lag_to_inflow_peak_seconds",
]:
    summary[column.replace("_seconds", "_hours")] = pd.to_numeric(summary[column], errors="coerce") / 3600.0

px.scatter(
    summary,
    x="time_to_peak_hours",
    y="peak_discharge_cms",
    hover_name="state_id",
    color="peak_attenuation_ratio",
    title="Peak magnitude vs. time to peak",
)

## Merge RAPID outputs with base network metrics

For `independent-units`, each child state corresponds to one collapsed base unit. The merge below combines:

- `rapid_run_registry.csv`
- `transition_registry.csv`
- base `collapse_ranking.csv`

so you can compare outlet hydrograph behavior against the original unit metrics such as `equivalent_length`, `elongation`, and `topologic_complexity_score`.

In [527]:
transition_registry = pd.read_csv(experiment_dir / "transition_registry.csv")
base_collapse_ranking = pd.read_csv(experiment_dir / "states" / "S000_base" / "hierarchy" / "collapse_ranking.csv")

def parse_single_unit_id(value):
    if pd.isna(value):
        return pd.NA
    parts = [part.strip() for part in str(value).split(",") if part.strip()]
    if len(parts) != 1:
        return pd.NA
    return int(parts[0])

transition_registry["unit_id"] = transition_registry["selected_unit_ids"].apply(parse_single_unit_id).astype("Int64")
base_collapse_ranking["unit_id"] = pd.to_numeric(base_collapse_ranking["unit_id"], errors="coerce").astype("Int64")

analysis = summary.merge(
    transition_registry[["child_state_id", "unit_id", "collapsed_selection_label", "selected_collapse_order", "selected_collapse_priority_score"]],
    left_on="state_id",
    right_on="child_state_id",
    how="left",
)
analysis = analysis.merge(
    base_collapse_ranking,
    on="unit_id",
    how="left",
    suffixes=("", "_network"),
)

analysis["unit_id"] = analysis["unit_id"].astype("Int64")
analysis.head()

,state_id,rapid_prep_dir,rapid_run_dir,qout_nc,status,hydrograph_status,outlet_hydrograph_csv,hydrograph_metrics_csv,hydrograph_metrics_json,event_definition_version,...,unit_node_ids,unit_node_count,unit_topodynamic_class,path_disparity_width_rank_component,elongation_rank_component,equivalent_length_rank_component,topologic_complexity_score_rank_component,collapse_priority_score,collapse_order_global,collapse_order_in_bubble
0,S000_base,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S001_unit_28,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"55,56",2.0,dominant_simple_split,1.000000,1.000000,1.000000,0.892157,0.973039,1.0,1.0
2,S002_unit_33,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"62,63",2.0,dominant_simple_split,0.960784,0.921569,0.901961,0.892157,0.919118,2.0,1.0
3,S003_unit_29,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"57,58",2.0,dominant_simple_split,0.764706,0.882353,0.803922,0.892157,0.835784,3.0,1.0
4,S004_unit_2,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,ran,computed,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,/Users/6256481/Code/river-hierarchy/network_va...,v2_local_min,...,"5,7",2.0,dominant_simple_split,0.803922,0.823529,0.745098,0.892157,0.816176,4.0,1.0

In [528]:
comparison_cols = [
    "state_id",
    "unit_id",
    "collapsed_selection_label",
    "peak_discharge_cms",
    "peak_excess_cms",
    "time_to_peak_hours",
    "peak_attenuation_ratio",
    "equivalent_length",
    "elongation",
    "effective_n_paths_width",
    "path_disparity_width",
    "topologic_complexity_score",
    "collapse_priority_score",
    "collapse_order_global",
]
analysis[comparison_cols].sort_values("peak_discharge_cms", ascending=False)

,state_id,unit_id,collapsed_selection_label,peak_discharge_cms,peak_excess_cms,time_to_peak_hours,peak_attenuation_ratio,equivalent_length,elongation,effective_n_paths_width,path_disparity_width,topologic_complexity_score,collapse_priority_score,collapse_order_global
44,S046_unit_10,10,collapsed_unit_10,2431.794794,912.728429,179.4,0.923987,1527.503259,9.868908,1.949146,1.026090,2.197225,0.200980,46.0
50,S052_unit_46,46,collapsed_unit_46,2430.016884,911.187722,179.1,0.923311,1256.626569,7.071783,1.964709,1.017962,3.295837,0.085784,52.0
33,S035_unit_1,1,collapsed_unit_1,2429.512896,916.476336,180.0,0.923120,640.685510,2.737434,1.792455,1.115788,2.484907,0.372549,35.0
49,S051_unit_51,51,collapsed_unit_51,2429.223832,907.670393,178.2,0.923010,1812.440210,3.299438,2.949330,1.017180,2.772589,0.129902,51.0
43,S045_unit_47,47,collapsed_unit_47,2427.559255,917.300255,180.0,0.922378,676.002616,5.748915,1.997811,1.001096,1.791759,0.237745,45.0
32,S034_unit_26,26,collapsed_unit_26,2427.301392,907.494179,177.9,0.922280,969.350112,1.371095,2.622645,1.143883,2.772589,0.404412,34.0
39,S041_unit_20,20,collapsed_unit_20,2427.108957,914.958408,179.7,0.922206,1682.185633,3.508595,2.334495,1.285074,3.178054,0.306373,41.0
4,S004_unit_2,2,collapsed_unit_2,2426.954081,912.166395,179.1,0.922148,395.415364,0.809090,1.670688,1.197112,1.098612,0.816176,4.0
41,S043_unit_12,12,collapsed_unit_12,2426.592603,913.728174,179.4,0.922010,1338.397639,2.126452,2.747257,1.091998,3.178054,0.281863,43.0
1,S001_unit_28,28,collapsed_unit_28,2426.516309,913.511319,179.4,0.921981,158.994781,0.285108,1.435446,1.393295,1.098612,0.973039,1.0
24,S026_unit_4,4,collapsed_unit_4,2425.831976,914.009416,179.4,0.921721,1025.358480,2.506279,1.604086,1.246816,1.791759,0.468137,26.0
3,S003_unit_29,29,collapsed_unit_29,2425.483838,915.677012,179.7,0.921589,330.916236,0.773831,1.685291,1.186738,1.098612,0.835784,3.0
9,S009_unit_25,25,collapsed_unit_25,2425.481613,910.998606,178.8,0.921588,529.726733,1.113518,1.455079,1.374496,1.098612,0.727941,9.0
13,S013_unit_14,14,collapsed_unit_14,2425.397330,917.924052,180.0,0.921556,207.962672,1.058474,1.853643,1.078957,1.791759,0.688725,13.0
45,S047_unit_48,48,collapsed_unit_48,2425.313078,935.886629,182.4,0.921524,673.056409,1.685030,2.953125,1.015873,3.871201,0.200980,47.0
40,S042_unit_43,43,collapsed_unit_43,2425.253302,916.130576,179.7,0.921501,548.083856,1.426138,1.963906,1.018378,2.890372,0.306373,42.0
47,S049_unit_49,49,collapsed_unit_49,2425.190497,916.364076,180.0,0.921477,843.379735,4.353087,1.999366,1.000317,2.484907,0.161765,49.0
8,S008_unit_18,18,collapsed_unit_18,2425.033168,928.879335,181.5,0.921418,397.881749,0.937630,1.582174,1.264084,1.791759,0.737745,8.0
16,S017_unit_7,7,collapsed_unit_7,2424.942598,918.417386,180.3,0.921383,460.582597,0.990106,1.677872,1.191986,1.791759,0.659314,17.0
48,S050_unit_31,31,collapsed_unit_31,2424.569856,907.533733,177.9,0.921242,2575.495446,2.403253,5.755322,1.042513,5.164786,0.156863,50.0
34,S036_unit_21,21,collapsed_unit_21,2424.558870,934.128921,182.1,0.921237,1481.279278,3.546323,1.826999,1.094691,1.791759,0.370098,36.0
7,S007_unit_24,24,collapsed_unit_24,2424.533245,912.435869,179.1,0.921228,316.469059,0.682400,1.950113,1.025582,1.098612,0.737745,7.0
19,S020_unit_27,27,collapsed_unit_27,2424.421645,915.868316,179.7,0.921185,425.469114,1.265245,1.909113,1.047607,1.098612,0.610294,20.0
21,S023_unit_11,11,collapsed_unit_11,2424.343066,926.492192,181.2,0.921155,585.464558,1.252030,1.611562,1.241032,2.197225,0.544118,23.0
17,S018_unit_3,3,collapsed_unit_3,2424.318974,924.363527,180.9,0.921146,277.647939,0.776090,1.958632,1.021121,1.791759,0.649510,18.0
36,S038_unit_22,22,collapsed_unit_22,2424.287391,942.386058,183.0,0.921134,894.648558,4.365288,1.866092,1.071759,1.791759,0.360294,38.0
46,S048_unit_15,15,collapsed_unit_15,2424.283477,931.656943,181.8,0.921133,1253.322715,4.405827,1.884575,1.061247,3.295837,0.178922,48.0
26,S028_unit_41,41,collapsed_unit_41,2424.279255,922.469277,180.9,0.921131,713.886368,1.371692,1.877796,1.065078,1.791759,0.448529,28.0
5,S005_unit_16,16,collapsed_unit_16,2424.013769,918.708232,180.3,0.921030,396.973590,0.994603,1.654712,1.208670,1.098612,0.772059,5.0
35,S037_unit_30,30,collapsed_unit_30,2424.008400,922.348469,180.9,0.921028,1207.955322,4.737181,1.942417,1.029645,1.098612,0.365196,37.0
6,S006_unit_23,23,collapsed_unit_23,2423.892949,924.768278,181.2,0.920984,197.296010,1.473757,1.790224,1.117179,1.098612,0.747549,6.0
30,S032_unit_35,35,collapsed_unit_35,2423.889438,923.043947,180.9,0.920983,591.148748,2.229047,1.964267,1.018192,1.098612,0.424020,32.0
22,S024_unit_8,8,collapsed_unit_8,2423.833283,925.218439,181.2,0.920962,629.180384,2.230468,1.596784,1.252517,1.791759,0.522059,24.0
27,S029_unit_36,36,collapsed_unit_36,2423.752826,925.003925,181.2,0.920931,452.841139,1.023979,1.954406,1.023329,2.484907,0.446078,29.0
2,S002_unit_33,33,collapsed_unit_33,2423.710535,920.701908,180.6,0.920915,257.726247,0.656442,1.528138,1.308783,1.098612,0.919118,2.0
20,S021_unit_38,38,collapsed_unit_38,2423.699958,923.722455,180.9,0.920911,322.023586,0.640306,1.950349,1.025458,2.484907,0.588235,21.0
10,S010_unit_34,34,collapsed_unit_34,2423.689011,922.859891,180.9,0.920907,232.686563,0.787713,1.858455,1.076163,1.791759,0.727941,10.0
18,S019_unit_42,42,collapsed_unit_42,2423.657683,925.137945,181.2,0.920895,417.534129,0.973634,1.884468,1.061307,1.791759,0.610294,19.0
0,S000_base,<NA>,NaN,2423.624516,924.552291,180.9,0.920882,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,S012_unit_40,40,collapsed_unit_40,2423.613207,923.829754,180.9,0.920878,381.918257,0.874464,1.801465,1.110208,1.791759,0.708333,12.0
15,S016_unit_37,37,collapsed_unit_37,2423.609339,921.792833,180.6,0.920877,312.584405,0.635292,1.854256,1.078600,2.484907,0.666667,16.0
31,S033_unit_50,50,collapsed_unit_50,2423.596366,920.635335,180.6,0.920872,573.886320,1.896217,1.877557,1.065214,2.197225,0.416667,33.0
11,S011_unit_6,6,collapsed_unit_6,2423.371698,922.375133,180.9,0.920786,353.810273,0.931900,1.760964,1.135741,1.791759,0.718137,11.0
38,S040_unit_32,32,collapsed_unit_32,2422.926419,922.428728,180.9,0.920617,588.806299,1.078162,2.884042,1.040207,3.465736,0.343137,40.0
28,S030_unit_39,39,collapsed_unit_39,2422.889201,929.472338,181.5,0.920603,455.337722,0.859529,1.991886,1.004074,2.484907,0.431373,30.0
14,S015_unit_17,17,collapsed_unit_17,2422.485921,927.118517,181.2,0.920450,230.340202,0.565348,1.962218,1.019255,1.791759,0.683824,15.0
29,S031_unit_45,45,collapsed_unit_45,2422.301855,921.379704,180.6,0.920380,491.612529,1.883619,1.959826,1.020499,1.791759,0.428922,31.0
37,S039_unit_9,9,collapsed_unit_9,2421.368802,933.803251,182.1,0.920025,511.113471,0.966404,1.981531,1.009321,2.890372,0.360294,39.0
42,S044_unit_19,19,collapsed_unit_19,2420.740558,926.712950,181.2,0.919787,605.920553,2.149522,1.953158,1.023983,2.890372,0.274510,44.0
23,S025_unit_44,44,collapsed_unit_44,2420.493461,936.295431,182.4,0.919693,553.946472,1.221216,1.829815,1.093007,2.484907,0.475490,25.0
25,S027_unit_52,52,collapsed_unit_52,2420.082978,990.136084,186.6,0.919537,460.783203,1.809386,1.983741,1.008196,1.098612,0.468137,27.0

In [529]:
network_metric_columns = [
    "equivalent_length",
    "elongation",
    "effective_n_paths_width",
    "path_disparity_width",
    "topologic_complexity_score",
    "collapse_priority_score",
]

plot_df = analysis.loc[analysis["unit_id"].notna()].copy()
plot_df["unit_id"] = plot_df["unit_id"].astype(int)
plot_df["state_label"] = plot_df["state_id"] + " | unit " + plot_df["unit_id"].astype(str)

network_vs_peak = plot_df.melt(
    id_vars=["state_id", "state_label", "unit_id", "peak_discharge_cms", "peak_attenuation_ratio", "time_to_peak_hours"],
    value_vars=network_metric_columns,
    var_name="network_metric",
    value_name="network_value",
).dropna(subset=["network_value"])

px.scatter(
    network_vs_peak,
    x="network_value",
    y="peak_discharge_cms",
    facet_col="network_metric",
    facet_col_wrap=3,
    hover_name="state_label",
    color="peak_attenuation_ratio",
    title="Peak discharge vs. selected network metrics",
)

In [530]:
corr_columns = [
    "peak_discharge_cms",
    "peak_excess_cms",
    "time_to_peak_hours",
    "fall_time_50_hours",
    "peak_attenuation_ratio",
    "equivalent_length",
    "elongation",
    "effective_n_paths_width",
    "path_disparity_width",
    "topologic_complexity_score",
    "collapse_priority_score",
]

corr_df = analysis.loc[analysis["unit_id"].notna(), corr_columns].apply(pd.to_numeric, errors="coerce")
corr = corr_df.corr(numeric_only=True)

px.imshow(
    corr,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Correlation between RAPID hydrograph metrics and network metrics",
)

## Expanded network predictors and bubble-membership analysis

This second analysis block keeps the original heatmap above, but broadens the network side with additional width and topology metrics and swaps the RAPID side to focus on:

- `time_to_peak_hours`
- `fall_time_10_hours`
- `peak_attenuation_ratio`
- `lag_to_inflow_peak_hours`
- `outlet_excess_volume_m3`
- `rise_rate_cms_per_hour`

It also adds a separate look at `time_to_peak` vs bubble membership.

In [531]:
analysis = analysis.copy()
analysis["lag_to_inflow_peak_hours"] = pd.to_numeric(analysis["lag_to_inflow_peak_seconds"], errors="coerce") / 3600.0
analysis["bubble_membership"] = analysis["in_compound_bubble"].map({True: "bubble_member", False: "standalone"}).fillna("unknown")

rapid_metric_columns_expanded = [
    "time_to_peak_hours",
    "fall_time_10_hours",
]

network_metric_candidates_expanded = [
    "bifurcation",
    "confluence",
    "equivalent_width",
    "equivalent_length",
    "n_paths",
    "n_valid_paths",
    "elongation",
    "path_length_min",
    "path_length_max",
    "path_length_mean",
    # "path_length_range",
    "path_length_range_norm",
    "path_length_cv",
    "path_width_eq_min",
    # "path_width_eq_max",
    "path_width_eq_mean",
    "path_width_range",
    "path_width_range_norm",
    "largest_path_width_fraction",
    "dominant_width_fraction",
    "width_entropy",
    "width_evenness",
    "effective_n_paths_width",
    "path_disparity_width",
    "width_ratio_2",
    "smaller_width_fraction_2",
    "dominant_width_fraction_2",
    "length_ratio_2",
    "internal_bifurcation_count",
    # "internal_confluence_count",
    "total_bifurcation_count",
    # "total_confluence_count",
    "internal_branch_node_count",
    "branching_density_by_length",
    "path_redundancy",
    "compound_indicator",
    # "topologic_complexity_score",
    "dynamic_proxy_entropy",
    "effective_n_paths_dyn_width",
    "dominant_dyn_fraction_width",
    "dynamic_proxy_complexity_score",
    "unit_node_count",
    "depth_from_root",
    "collapse_level",
    "n_children",
    "n_descendants",
    # "path_disparity_width_rank_component",
    # "elongation_rank_component",
    # "equivalent_length_rank_component",
    # "topologic_complexity_score_rank_component",
    "collapse_priority_score",
]

available_network_metrics_expanded = [
    column for column in network_metric_candidates_expanded if column in analysis.columns
]

available_network_metrics_expanded

['bifurcation',
 'confluence',
 'equivalent_width',
 'equivalent_length',
 'n_paths',
 'n_valid_paths',
 'elongation',
 'path_length_min',
 'path_length_max',
 'path_length_mean',
 'path_length_range_norm',
 'path_length_cv',
 'path_width_eq_min',
 'path_width_eq_mean',
 'path_width_range',
 'path_width_range_norm',
 'largest_path_width_fraction',
 'dominant_width_fraction',
 'width_entropy',
 'width_evenness',
 'effective_n_paths_width',
 'path_disparity_width',
 'width_ratio_2',
 'smaller_width_fraction_2',
 'dominant_width_fraction_2',
 'length_ratio_2',
 'internal_bifurcation_count',
 'total_bifurcation_count',
 'internal_branch_node_count',
 'branching_density_by_length',
 'path_redundancy',
 'compound_indicator',
 'dynamic_proxy_entropy',
 'effective_n_paths_dyn_width',
 'dominant_dyn_fraction_width',
 'dynamic_proxy_complexity_score',
 'unit_node_count',
 'depth_from_root',
 'collapse_level',
 'n_children',
 'n_descendants',
 'collapse_priority_score']

In [532]:
corr_columns_expanded = rapid_metric_columns_expanded + available_network_metrics_expanded
corr_df_expanded = analysis.loc[analysis["unit_id"].notna(), corr_columns_expanded].apply(pd.to_numeric, errors="coerce")
corr_expanded = corr_df_expanded.corr(numeric_only=True)
cross_corr = corr_expanded.loc[rapid_metric_columns_expanded, available_network_metrics_expanded]

fig = px.imshow(
    cross_corr,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Cross-domain correlations: time to peak and fall time vs. network metrics",
)
fig.update_xaxes(title="Network metrics")
fig.update_yaxes(title="RAPID metrics")
fig

In [ ]:
- equivalent length
- elongation
-

In [533]:
cross_domain_rows = []
for rapid_metric in rapid_metric_columns_expanded:
    for network_metric in available_network_metrics_expanded:
        corr_value = cross_corr.loc[rapid_metric, network_metric]
        cross_domain_rows.append(
            {
                "rapid_metric": rapid_metric,
                "network_metric": network_metric,
                "correlation": corr_value,
                "abs_correlation": abs(corr_value),
            }
        )

cross_domain_corr = pd.DataFrame(cross_domain_rows).sort_values("abs_correlation", ascending=False)
cross_domain_corr.head(20)

,rapid_metric,network_metric,correlation,abs_correlation
39,time_to_peak_hours,n_children,-0.357783,0.357783
40,time_to_peak_hours,n_descendants,-0.357783,0.357783
8,time_to_peak_hours,path_length_max,-0.354369,0.354369
4,time_to_peak_hours,n_paths,-0.352723,0.352723
5,time_to_peak_hours,n_valid_paths,-0.352723,0.352723
30,time_to_peak_hours,path_redundancy,-0.352723,0.352723
2,time_to_peak_hours,equivalent_width,-0.346004,0.346004
79,fall_time_10_hours,depth_from_root,-0.343862,0.343862
9,time_to_peak_hours,path_length_mean,-0.342467,0.342467
3,time_to_peak_hours,equivalent_length,-0.319674,0.319674
7,time_to_peak_hours,path_length_min,-0.316394,0.316394
38,time_to_peak_hours,collapse_level,-0.314366,0.314366
31,time_to_peak_hours,compound_indicator,-0.314366,0.314366
14,time_to_peak_hours,path_width_range,-0.298508,0.298508
33,time_to_peak_hours,effective_n_paths_dyn_width,-0.272852,0.272852
20,time_to_peak_hours,effective_n_paths_width,-0.272852,0.272852
42,fall_time_10_hours,bifurcation,-0.249364,0.249364
43,fall_time_10_hours,confluence,-0.248382,0.248382
24,time_to_peak_hours,dominant_width_fraction_2,-0.238945,0.238945
23,time_to_peak_hours,smaller_width_fraction_2,0.238945,0.238945

In [534]:
px.bar(
    cross_domain_corr.head(15),
    x="abs_correlation",
    y="network_metric",
    color="rapid_metric",
    orientation="h",
    hover_data=["correlation"],
    title="Strongest RAPID vs. network correlations",
)

In [535]:
bubble_df = analysis.loc[analysis["unit_id"].notna()].copy()
bubble_df["unit_id"] = bubble_df["unit_id"].astype(int)
bubble_df["state_label"] = bubble_df["state_id"] + " | unit " + bubble_df["unit_id"].astype(str)

px.box(
    bubble_df,
    x="bubble_membership",
    y="time_to_peak_hours",
    color="bubble_membership",
    points="all",
    hover_name="state_label",
    title="Time to peak by bubble membership",
)

In [536]:
px.box(
    bubble_df,
    x="bubble_membership",
    y="fall_time_10_hours",
    color="bubble_membership",
    points="all",
    hover_name="state_label",
    title="Fall time 10 by bubble membership",
)

# RAPID vs K equivalent

In [74]:
from pathlib import Path

import pandas as pd
import plotly.express as px

exp_dir = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/56_compound_bubbles")

comparison_csv = exp_dir / "equivalent_resistance" / "equivalent_resistance_comparison.csv"
rapid_run_csv = exp_dir / "rapid_run_registry.csv"

comp = pd.read_csv(comparison_csv)
runs = pd.read_csv(rapid_run_csv)

plot_df = (
    comp.loc[comp["comparison_valid_for_matched"].fillna(False)].copy()
    .merge(
        runs[["state_id", "peak_time_seconds", "peak_time_utc", "status", "hydrograph_status"]],
        on="state_id",
        how="left",
    )
)

base_peak_time_seconds = float(
    runs.loc[runs["state_id"].eq("S000_base"), "peak_time_seconds"].iloc[0]
)

plot_df["peak_shift_vs_base_hours"] = (
    plot_df["peak_time_seconds"] - base_peak_time_seconds
) / 3600.0

plot_df["bubble_label"] = plot_df["state_id"].str.replace("CB", "bubble ", regex=False)

fig = px.scatter(
    plot_df,
    x="Lambda_matched",
    y="peak_shift_vs_base_hours",
    text="bubble_label",
    hover_data=[
        "state_id",
        "target_id",
        "child_object_id",
        "boundary_relation",
        "K_eq_matched_base",
        "K_variant_realized",
        "peak_time_utc",
    ],
    labels={
        "Lambda_matched": "Lambda_matched = K_variant_realized / K_eq_matched_base",
        "peak_shift_vs_base_hours": "Peak shift vs base [hours]",
    },
    title="56 Compound Bubbles: Peak Shift vs Lambda_matched",
)

fig.update_traces(marker=dict(size=12, line=dict(width=1, color="black")))
fig.update_traces(textposition="top center")
fig.update_xaxes(type="log")
fig.add_hline(y=0.0, line_dash="dash", line_color="gray")
fig.show()

plot_df[[
    "state_id",
    "target_id",
    "Lambda_matched",
    "peak_shift_vs_base_hours",
    "boundary_relation",
    "K_eq_matched_base",
    "K_variant_realized",
]]

FileNotFoundError: [Errno 2] No such file or directory: '/Users/6256481/Code/river-hierarchy/network_variants/output/56_compound_bubbles/equivalent_resistance/equivalent_resistance_comparison.csv'

In [120]:
from pathlib import Path

import pandas as pd
import plotly.express as px

root = Path("/Users/6256481/Code/river-hierarchy/network_variants/output")

experiments = {
    "indep": root / "56_indep__anchored",
    "compound": root / "56_compound_bubbles__anchored",
}

def load_peak_vs_lambda(exp_dir: Path, mode_label: str) -> pd.DataFrame:
    comp = pd.read_csv(exp_dir / "equivalent_resistance" / "equivalent_resistance_comparison.csv")
    runs = pd.read_csv(exp_dir / "rapid_run_registry.csv")

    df = (
        comp.loc[comp["comparison_valid_for_matched"].fillna(False)].copy()
        .merge(
            runs[["state_id", "peak_time_seconds", "peak_time_utc", "status", "hydrograph_status"]],
            on="state_id",
            how="left",
        )
    )

    base_peak_time_seconds = float(
        runs.loc[runs["state_id"].eq("S000_base"), "peak_time_seconds"].iloc[0]
    )

    df["peak_shift_vs_base_hours"] = (
        df["peak_time_seconds"] - base_peak_time_seconds
    ) / 3600.0

    df["mode"] = mode_label
    df["target_label"] = df.apply(
        lambda r: f"bubble {int(r['target_id'])}" if r["target_type"] == "compound_bubble" else f"unit {int(r['target_id'])}",
        axis=1,
    )
    return df

plot_df = pd.concat(
    [load_peak_vs_lambda(exp_dir, mode) for mode, exp_dir in experiments.items()],
    ignore_index=True,
)

fig = px.scatter(
    plot_df,
    x="Lambda_matched",
    y="peak_shift_vs_base_hours",
    color="mode",
    text="target_label",
    hover_data=[
        "state_id",
        "target_type",
        "target_id",
        "child_object_id",
        "boundary_relation",
        "K_eq_matched_base",
        "K_variant_realized",
        "peak_time_utc",
    ],
    color_discrete_map={
        "indep": "#1f77b4",
        "compound": "#d62728",
    },
    labels={
        "Lambda_matched": "Lambda_matched = K_variant_realized / K_eq_matched_base",
        "peak_shift_vs_base_hours": "Peak shift vs base [hours]",
        "mode": "Experiment type",
    },
    title="56: Peak Shift vs Lambda_matched",
)

fig.update_traces(marker=dict(size=12, line=dict(width=1, color="black")))
fig.update_traces(textposition="top center")
fig.update_xaxes(type="log")
fig.add_hline(y=0.0, line_dash="dash", line_color="gray")
fig.show()

plot_df[[
    "mode",
    "state_id",
    "target_type",
    "target_id",
    "Lambda_matched",
    "peak_shift_vs_base_hours",
    "boundary_relation",
]]

,mode,state_id,target_type,target_id,Lambda_matched,peak_shift_vs_base_hours,boundary_relation
0,indep,S001_unit_13,unit,13,0.751979,-0.6,exact_match
1,indep,S002_unit_14,unit,14,0.623941,-0.3,exact_match
2,indep,S003_unit_3,unit,3,0.196299,-0.9,exact_match
3,indep,S004_unit_9,unit,9,0.434069,-0.9,exact_match
4,indep,S006_unit_15,unit,15,0.188454,-12.6,exact_match
5,indep,S007_unit_11,unit,11,0.148729,-1.8,exact_match
6,indep,S008_unit_6,unit,6,0.230801,-6.0,exact_match
7,indep,S013_unit_12,unit,12,0.082635,-17.4,exact_match
8,indep,S014_unit_10,unit,10,0.069899,-19.8,exact_match
9,indep,S015_unit_4,unit,4,0.100325,-23.1,exact_match
10,compound,CB001_bubble_8,compound_bubble,8,0.109299,-29.1,expanded_downstream
11,compound,CB002_bubble_4,compound_bubble,4,0.082635,-17.4,exact_match
12,compound,CB003_bubble_5,compound_bubble,5,0.069899,-19.8,exact_match
13,compound,CB004_bubble_6,compound_bubble,6,0.166143,-6.0,expanded_downstream
14,compound,CB005_bubble_9,compound_bubble,9,0.093154,-27.3,expanded_downstream

In [186]:
from pathlib import Path

import numpy as np
import pandas as pd

EXP_DIR = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/56_indep__anchored")
STATES_DIR = EXP_DIR / "states"

def load_outlet(state_id: str) -> pd.DataFrame:
    df = pd.read_csv(STATES_DIR / state_id / "rapid" / "run" / "outlet_hydrograph.csv")
    df = df[["time_seconds", "time_utc", "q_outlet_cms"]].copy()
    df["time_utc"] = pd.to_datetime(df["time_utc"], utc=True)
    return df

def interp_first_crossing_time(t, q, level):
    idx = np.where(q >= level)[0]
    if len(idx) == 0:
        return np.nan
    i = int(idx[0])
    if i == 0:
        return float(t[0])
    t0, t1 = float(t[i - 1]), float(t[i])
    q0, q1 = float(q[i - 1]), float(q[i])
    if q1 == q0:
        return t1
    return t0 + (level - q0) * (t1 - t0) / (q1 - q0)

def plateau_center_time(t, q, frac=0.995):
    peak = float(np.max(q))
    mask = q >= peak * frac
    if not np.any(mask):
        return np.nan
    return float(np.mean(t[mask]))

def weighted_centroid_time(t, q, frac=0.5):
    peak = float(np.max(q))
    threshold = peak * frac
    mask = q >= threshold
    if not np.any(mask):
        return np.nan
    weights = q[mask] - threshold
    if np.allclose(weights.sum(), 0):
        return float(np.mean(t[mask]))
    return float(np.sum(t[mask] * weights) / np.sum(weights))

def xcorr_lag_hours(q_base, q_other, dt_seconds):
    qb = np.asarray(q_base, dtype=float) - np.mean(q_base)
    qo = np.asarray(q_other, dtype=float) - np.mean(q_other)
    corr = np.correlate(qo, qb, mode="full")
    lags = np.arange(-len(qo) + 1, len(qo))
    best_lag_steps = int(lags[np.argmax(corr)])
    return best_lag_steps * dt_seconds / 3600.0

run = pd.read_csv(EXP_DIR / "rapid_run_registry.csv")
comp = pd.read_csv(EXP_DIR / "equivalent_resistance" / "equivalent_resistance_comparison.csv")

state_ids = run.loc[run["state_id"].ne("S000_base"), "state_id"].tolist()

base = load_outlet("S000_base")
t_base = base["time_seconds"].to_numpy()
q_base = base["q_outlet_cms"].to_numpy()
dt_seconds = float(np.median(np.diff(t_base)))

base_metrics = {
    "peak_time_seconds": float(t_base[np.argmax(q_base)]),
    "rise95_time_seconds": interp_first_crossing_time(t_base, q_base, 0.95 * np.max(q_base)),
    "rise99_time_seconds": interp_first_crossing_time(t_base, q_base, 0.99 * np.max(q_base)),
    "plateau995_center_seconds": plateau_center_time(t_base, q_base, frac=0.995),
    "plateau999_center_seconds": plateau_center_time(t_base, q_base, frac=0.999),
    "centroid50_seconds": weighted_centroid_time(t_base, q_base, frac=0.50),
    "centroid75_seconds": weighted_centroid_time(t_base, q_base, frac=0.75),
}

rows = []
for state_id in state_ids:
    df = load_outlet(state_id)
    t = df["time_seconds"].to_numpy()
    q = df["q_outlet_cms"].to_numpy()

    metrics = {
        "state_id": state_id,
        "peak_time_seconds": float(t[np.argmax(q)]),
        "rise95_time_seconds": interp_first_crossing_time(t, q, 0.95 * np.max(q)),
        "rise99_time_seconds": interp_first_crossing_time(t, q, 0.99 * np.max(q)),
        "plateau995_center_seconds": plateau_center_time(t, q, frac=0.995),
        "plateau999_center_seconds": plateau_center_time(t, q, frac=0.999),
        "centroid50_seconds": weighted_centroid_time(t, q, frac=0.50),
        "centroid75_seconds": weighted_centroid_time(t, q, frac=0.75),
        "xcorr_lag_hours": xcorr_lag_hours(q_base, q, dt_seconds),
    }

    for key, base_value in base_metrics.items():
        shift_name = key.replace("_seconds", "_shift_hours")
        metrics[shift_name] = (metrics[key] - base_value) / 3600.0

    rows.append(metrics)

summary = pd.DataFrame(rows).merge(
    comp[[
        "state_id",
        "target_id",
        "Lambda_matched",
        "boundary_relation",
        "comparison_valid_for_matched",
    ]],
    on="state_id",
    how="left",
)

display_cols = [
    "state_id",
    "target_id",
    "Lambda_matched",
    "boundary_relation",
    "peak_time_shift_hours",
    "rise95_time_shift_hours",
    "rise99_time_shift_hours",
    "plateau995_center_shift_hours",
    "plateau999_center_shift_hours",
    "centroid50_shift_hours",
    "centroid75_shift_hours",
    "xcorr_lag_hours",
]

summary.sort_values("peak_time_shift_hours")[display_cols]
# /Users/6256481/Code/river-hierarchy/network_variants/output/56_indep__anchored

,state_id,target_id,Lambda_matched,boundary_relation,peak_time_shift_hours,rise95_time_shift_hours,rise99_time_shift_hours,plateau995_center_shift_hours,plateau999_center_shift_hours,centroid50_shift_hours,centroid75_shift_hours,xcorr_lag_hours
14,S015_unit_4,4,0.185198,exact_match,-23.4,-21.350793,-22.654261,-23.55,-23.70,-14.345120,-23.396516,-4.5
13,S014_unit_10,10,0.142897,exact_match,-17.1,-16.869114,-16.970184,-17.10,-17.10,-11.362042,-17.120061,-0.3
12,S013_unit_12,12,0.145345,exact_match,-13.2,-12.952554,-13.087079,-13.35,-13.20,-8.647776,-13.283457,0.0
5,S006_unit_15,15,0.230440,exact_match,-11.4,-11.381434,-11.392972,-11.40,-11.40,-7.610246,-11.412491,0.0
8,S009_unit_1,1,NaN,ambiguous,-11.1,-12.431969,-11.749779,-11.40,-11.25,-8.786436,-10.782248,0.0
7,S008_unit_6,6,0.251355,exact_match,-5.1,-4.961137,-5.018447,-5.10,-5.10,-3.270601,-5.107266,0.0
11,S012_unit_2,2,NaN,ambiguous,-4.5,-4.491594,-4.516110,-4.65,-4.50,-2.962595,-4.552307,0.0
9,S010_unit_8,8,NaN,ambiguous,-3.3,-3.402251,-3.413348,-3.45,-3.60,-2.238010,-3.427343,0.0
10,S011_unit_5,5,NaN,ambiguous,-3.3,-2.868892,-3.195827,-3.45,-3.45,-1.634317,-3.274643,0.0
4,S005_unit_7,7,NaN,ambiguous,-1.2,-1.205422,-1.231933,-1.35,-1.35,-0.788285,-1.274340,0.0
6,S007_unit_11,11,0.126380,exact_match,-1.2,-1.214393,-1.252796,-1.35,-1.35,-0.786519,-1.309726,0.0
0,S001_unit_13,13,0.677665,exact_match,-0.6,-0.724452,-0.742424,-0.75,-0.90,-0.473353,-0.771760,0.0
1,S002_unit_14,14,0.617577,exact_match,-0.6,-0.475839,-0.495229,-0.60,-0.60,-0.310346,-0.527454,0.0
2,S003_unit_3,3,0.281319,exact_match,-0.6,-1.028536,-0.865381,-0.90,-0.90,-0.677793,-0.782560,0.0
3,S004_unit_9,9,0.463051,exact_match,-0.3,-0.426653,-0.446148,-0.45,-0.60,-0.276845,-0.477557,0.0

In [187]:
import plotly.express as px

plot_df = summary.loc[summary["comparison_valid_for_matched"].fillna(False)].copy()

fig = px.scatter(
    plot_df,
    x="Lambda_matched",
    y="centroid50_shift_hours",
    hover_data=[
        "state_id",
        "target_id",
        "boundary_relation",
        "peak_time_shift_hours",
        "rise95_time_shift_hours",
        "plateau995_center_shift_hours",
        "xcorr_lag_hours",
    ],
    labels={
        "Lambda_matched": "Lambda_matched",
        "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
    },
    title="56_indep: Stable Timing Shift vs Lambda_matched",
)

fig.update_traces(marker=dict(size=11, line=dict(width=1, color="black")))
fig.update_xaxes(type="log")
fig.add_hline(y=0, line_dash="dash", line_color="gray")
fig.show()

In [209]:
kb = 446.82
Cz = 22

def RK(l, w):
    d = w / kb
    A = w*d
    print(d, A)
    return l / (Cz**2*9.81*A**2*d)
ls = 1285.31171461144
ls = 12850.31171461144
ws = 335.7159452297721
Ks = RK(ls,ws)



l1 = 1381.0255268105757
l1 = 13810.0255268105757
w1 = 206
K1 = RK(l1,w1)

l2 = 1344.956866344332
l2 = 13440.956866344332
w2 = 115
K2 = RK(l2,w2)
print(Ks, K1, K2)


K_eq = 1/((1/np.sqrt(K1))+ (1/np.sqrt(K2)))**2
K_eq, Ks / K_eq

0.7513449380729871 252.23847607877744
0.46103576384226314 94.97336735150621
0.25737433418378763 29.598048431135577
5.661574948510443e-05 0.000699426081655095 0.012555222954544133

(0.0004578118708271987, 0.1236659708775312)

In [210]:
from pathlib import Path
import json

import numpy as np
import pandas as pd
import geopandas as gpd
import plotly.express as px

# Anchored experiment root
EXP_DIR = Path("/Users/6256481/Code/river-hierarchy/network_variants/output/56_indep__anchored")

# -------------------------------------------------------------------
# Inputs already produced by your anchored workflow
# -------------------------------------------------------------------
comp = pd.read_csv(EXP_DIR / "equivalent_resistance" / "equivalent_resistance_comparison.csv")
matched = pd.read_csv(EXP_DIR / "equivalent_resistance" / "matched_base_corridors.csv")
child = pd.read_csv(EXP_DIR / "equivalent_resistance" / "child_realized_objects.csv")

# Assumes `summary` already exists from your previous notebook cell.
# If it does not, run that cell first.
plot_df = summary.copy()

# Keep only valid matched comparisons
plot_df = plot_df.loc[plot_df["comparison_valid_for_matched"].fillna(False)].copy()

# Bring in the full anchored K/G metadata
plot_df = (
    plot_df.drop(columns=[c for c in ["K_eq_matched_base", "K_variant_realized"] if c in plot_df.columns], errors="ignore")
    .merge(
        comp[
            [
                "state_id",
                "child_object_id",
                "target_id",
                "Lambda_matched",
                "Gamma_matched",
                "K_eq_matched_base",
                "K_variant_realized",
                "boundary_relation",
                "comparison_valid_for_matched",
            ]
        ],
        on=["state_id", "target_id", "Lambda_matched", "boundary_relation", "comparison_valid_for_matched"],
        how="left",
    )
    .merge(
        matched[
            [
                "state_id",
                "child_object_id",
                "matched_base_link_ids",
                "matched_base_n_links",
                "G_eq_matched_base",
                "Q_unit_matched_base",
            ]
        ],
        on=["state_id", "child_object_id"],
        how="left",
    )
    .merge(
        child[
            [
                "state_id",
                "child_object_id",
                "child_link_ids",
                "child_object_type",
                "G_variant_realized",
                "Q_unit_variant",
            ]
        ],
        on=["state_id", "child_object_id"],
        how="left",
    )
)

# -------------------------------------------------------------------
# Recover matched-base corridor lengths from the existing base link table
# using the same length priority as the manifest.
# -------------------------------------------------------------------
manifest = json.loads((EXP_DIR / "equivalent_resistance" / "equivalent_resistance_manifest.json").read_text())
length_candidates = manifest["equivalent_resistance_config"]["length_field_candidates"]

base_links = gpd.read_file(EXP_DIR / "states" / "S000_base" / "variant" / "widths" / "links_with_width_families.gpkg")
length_field = next(c for c in length_candidates if c in base_links.columns)

base_len_lookup = (
    base_links[["id_link", length_field]]
    .rename(columns={length_field: "base_link_len"})
    .assign(id_link=lambda d: pd.to_numeric(d["id_link"], errors="coerce").astype("Int64"))
    .dropna(subset=["id_link"])
    .drop_duplicates(subset=["id_link"])
    .set_index("id_link")["base_link_len"]
)

total_base_len = float(base_len_lookup.sum())

def parse_int_list(value):
    if pd.isna(value):
        return []
    text = str(value).strip()
    if not text:
        return []
    return [int(float(x.strip())) for x in text.split(",") if x.strip()]

def sum_base_lengths(link_ids_text):
    ids = parse_int_list(link_ids_text)
    if not ids:
        return np.nan
    vals = base_len_lookup.reindex(ids)
    return float(vals.sum()) if vals.notna().any() else np.nan

plot_df["matched_base_len"] = plot_df["matched_base_link_ids"].map(sum_base_lengths)
plot_df["matched_len_frac"] = plot_df["matched_base_len"] / total_base_len

# -------------------------------------------------------------------
# Six geometry-only x-metrics
# -------------------------------------------------------------------
plot_df["neg_log10_lambda"] = -np.log10(plot_df["Lambda_matched"])
plot_df["delta_K"] = plot_df["K_eq_matched_base"] - plot_df["K_variant_realized"]
plot_df["delta_K_abs"] = plot_df["delta_K"].abs()
plot_df["delta_G"] = plot_df["G_variant_realized"] - plot_df["G_eq_matched_base"]
plot_df["delta_G_abs"] = plot_df["delta_G"].abs()
plot_df["length_weighted_log_lambda"] = plot_df["matched_len_frac"] * plot_df["neg_log10_lambda"]

# -------------------------------------------------------------------
# Common hover fields
# -------------------------------------------------------------------
hover_cols = [
    "state_id",
    "target_id",
    "child_object_id",
    "child_object_type",
    "boundary_relation",
    "peak_time_shift_hours",
    "rise95_time_shift_hours",
    "plateau995_center_shift_hours",
    "xcorr_lag_hours",
    "K_eq_matched_base",
    "K_variant_realized",
    "G_eq_matched_base",
    "G_variant_realized",
    "matched_base_n_links",
    "matched_base_len",
    "matched_len_frac",
]

# -------------------------------------------------------------------
# Plot helper
# -------------------------------------------------------------------
def make_scatter(df, x, title, x_label=None, log_x=False):
    fig = px.scatter(
        df,
        x=x,
        y="centroid50_shift_hours",
        hover_data=hover_cols,
        labels={
            x: x_label or x,
            "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
        },
        title=title,
    )
    fig.update_traces(marker=dict(size=11, line=dict(width=1, color="black")))
    if log_x:
        fig.update_xaxes(type="log")
    fig.add_hline(y=0, line_dash="dash", line_color="gray")
    fig.show()

# -------------------------------------------------------------------
# Six plots
# -------------------------------------------------------------------
make_scatter(
    plot_df,
    x="Lambda_matched",
    x_label="Lambda_matched = K_variant_realized / K_eq_matched_base",
    title="56_indep anchored: Centroid Shift vs Lambda_matched",
    log_x=True,
)

make_scatter(
    plot_df,
    x="neg_log10_lambda",
    x_label="-log10(Lambda_matched)",
    title="56_indep anchored: Centroid Shift vs -log10(Lambda_matched)",
    log_x=False,
)

make_scatter(
    plot_df,
    x="delta_K_abs",
    x_label="|K_eq_matched_base - K_variant_realized|",
    title="56_indep anchored: Centroid Shift vs Absolute Resistance Change",
    log_x=True,
)

make_scatter(
    plot_df,
    x="K_eq_matched_base",
    x_label="K_eq_matched_base",
    title="56_indep anchored: Centroid Shift vs Base Matched Resistance Magnitude",
    log_x=True,
)

make_scatter(
    plot_df,
    x="length_weighted_log_lambda",
    x_label="matched_len_frac * (-log10(Lambda_matched))",
    title="56_indep anchored: Centroid Shift vs Length-Weighted Resistance Change",
    log_x=False,
)

make_scatter(
    plot_df,
    x="delta_G_abs",
    x_label="|G_variant_realized - G_eq_matched_base|",
    title="56_indep anchored: Centroid Shift vs Absolute Conductance Change",
    log_x=True,
)

# -------------------------------------------------------------------
# Bonus plot: keep Lambda on x, but encode base importance separately
# -------------------------------------------------------------------
plot_df["log10_K_eq_matched_base"] = np.log10(plot_df["K_eq_matched_base"])

fig = px.scatter(
    plot_df,
    x="Lambda_matched",
    y="centroid50_shift_hours",
    color="log10_K_eq_matched_base",
    size="matched_len_frac",
    hover_data=hover_cols,
    labels={
        "Lambda_matched": "Lambda_matched",
        "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
        "log10_K_eq_matched_base": "log10(K_eq_matched_base)",
        "matched_len_frac": "Matched base length fraction",
    },
    title="56_indep anchored: Centroid Shift vs Lambda_matched, colored by K_eq and sized by matched length fraction",
)
fig.update_traces(marker=dict(line=dict(width=1, color="black")))
fig.update_xaxes(type="log")
fig.add_hline(y=0, line_dash="dash", line_color="gray")
fig.show()

,mode,state_id,target_type,target_id,Lambda_matched,matched_base_len,matched_len_frac,length_weighted_log_lambda,centroid50_shift_hours
13,compound,CB004_bubble_6,compound_bubble,6,0.189086,9486.300020,0.060397,0.043688,-3.382822
14,compound,CB005_bubble_9,compound_bubble,9,0.094271,8490.314503,0.054056,0.055441,-19.253016
11,compound,CB002_bubble_4,compound_bubble,4,0.145345,13461.373147,0.085705,0.071787,-8.647776
12,compound,CB003_bubble_5,compound_bubble,5,0.142897,24045.728530,0.153093,0.129360,-11.362042
10,compound,CB001_bubble_8,compound_bubble,8,0.201925,29600.535592,0.188460,0.130944,-15.073175
0,indep,S001_unit_13,unit,13,0.677665,3282.257070,0.020897,0.003531,-0.473353
1,indep,S002_unit_14,unit,14,0.617577,3824.431626,0.024349,0.005097,-0.310346
3,indep,S004_unit_9,unit,9,0.463051,3028.000865,0.019279,0.006446,-0.276845
2,indep,S003_unit_3,unit,3,0.281319,2730.090573,0.017382,0.009574,-0.677793
5,indep,S007_unit_11,unit,11,0.126380,2725.982393,0.017356,0.015591,-0.786519
4,indep,S006_unit_15,unit,15,0.230440,5435.679904,0.034608,0.022060,-7.610246
6,indep,S008_unit_6,unit,6,0.251355,7770.181511,0.049471,0.029668,-3.270601
7,indep,S013_unit_12,unit,12,0.145345,13461.373147,0.085705,0.071787,-8.647776
8,indep,S014_unit_10,unit,10,0.142897,24045.728530,0.153093,0.129360,-11.362042
9,indep,S015_unit_4,unit,4,0.185198,27907.878212,0.177683,0.130129,-14.345120

## Next Steps Plan

### RAPID Prep Spin-Up
- Implement a constant-flow forcing spin-up in `rapid_tools.forcing` and `rapid_tools.prep`.
- Use the first gauge discharge value as the spin-up discharge.
- Drive the spin-up from `ForcingConfig(spinup_hours=...)` and persist the resolved settings in the prep manifest.
- Start with `24 h` as the default working value for reruns unless a stronger network-fill estimate is available.

### Timing Metrics To Compare
- Keep `centroid50_shift_hours` for continuity.
- Add `centroid75`, `rise95`, `plateau995_center`, `xcorr_lag`, and robust peak-core metrics in a later section.
- Normalize robust peak-core timing shifts by an observed gauge-to-gauge travel time once that reference has been assembled.

### Geometry Context Additions
- Add along-network fractional distance coloring to identify outlet/upstream edge effects.
- Add an alternative length fraction based on `child length / matched parent length`.
- Compare both length-weighted scores against the current anchored timing plots.

## Geometry Context Diagnostics

This section extends the combined anchored `plot_df` built above. It adds:
- `plot_category`: one of `single unit`, `compound unit`, `nested unit`, or `part of compound unit`
- `along_network_frac`: a length-weighted parent-link midpoint distance-to-outlet fraction
- `child_parent_len_frac`: collapsed child length divided by matched parent-link length
- `child_parent_weighted_log_lambda`: `child_parent_len_frac * (-log10(Lambda_matched))`
- `width_fraction_of_total`: matched split-width fraction relative to the last upstream single-channel parent link, capped at `1.0`
- `child_parent_width_weighted_log_lambda`: `child_parent_len_frac * (-log10(Lambda_matched)) * width_fraction_of_total`

To rerun for another example, only change `EXAMPLE_ID` in the previous cell.

In [239]:
EXAMPLE_ID = "03"

In [240]:
from pathlib import Path
import json

import geopandas as gpd
import numpy as np
import pandas as pd
import plotly.express as px


ROOT = Path("/Users/6256481/Code/river-hierarchy/network_variants/output")

EXPERIMENT_NAMES = {
    "indep": f"{EXAMPLE_ID}_indep__anchored",
    "compound": f"{EXAMPLE_ID}_compound_bubbles__anchored",
}
EXPERIMENTS = {mode: ROOT / name for mode, name in EXPERIMENT_NAMES.items()}
PLOT_PREFIX = f"{EXAMPLE_ID} anchored"


def parse_int_list(value):
    if pd.isna(value):
        return []
    text = str(value).strip()
    if not text:
        return []
    return [int(float(x.strip())) for x in text.split(",") if x.strip()]


def interp_first_crossing_time(t, q, level):
    idx = np.where(q >= level)[0]
    if len(idx) == 0:
        return np.nan
    i = int(idx[0])
    if i == 0:
        return float(t[0])
    t0, t1 = float(t[i - 1]), float(t[i])
    q0, q1 = float(q[i - 1]), float(q[i])
    if q1 == q0:
        return t1
    return t0 + (level - q0) * (t1 - t0) / (q1 - q0)


def plateau_center_time(t, q, frac=0.995):
    peak = float(np.max(q))
    mask = q >= peak * frac
    if not np.any(mask):
        return np.nan
    return float(np.mean(t[mask]))


def weighted_centroid_time(t, q, frac=0.5):
    peak = float(np.max(q))
    threshold = peak * frac
    mask = q >= threshold
    if not np.any(mask):
        return np.nan
    weights = q[mask] - threshold
    if np.allclose(weights.sum(), 0):
        return float(np.mean(t[mask]))
    return float(np.sum(t[mask] * weights) / np.sum(weights))


def xcorr_lag_hours(q_base, q_other, dt_seconds):
    qb = np.asarray(q_base, dtype=float) - np.mean(q_base)
    qo = np.asarray(q_other, dtype=float) - np.mean(q_other)
    corr = np.correlate(qo, qb, mode="full")
    lags = np.arange(-len(qo) + 1, len(qo))
    best_lag_steps = int(lags[np.argmax(corr)])
    return best_lag_steps * dt_seconds / 3600.0


def load_outlet(states_dir: Path, state_id: str) -> pd.DataFrame:
    df = pd.read_csv(states_dir / state_id / "rapid" / "run" / "outlet_hydrograph.csv")
    df = df[["time_seconds", "time_utc", "q_outlet_cms"]].copy()
    df["time_utc"] = pd.to_datetime(df["time_utc"], utc=True)
    return df


def build_length_lookup(exp_dir: Path):
    manifest = json.loads((exp_dir / "equivalent_resistance" / "equivalent_resistance_manifest.json").read_text())
    length_candidates = manifest["equivalent_resistance_config"]["length_field_candidates"]

    base_links = gpd.read_file(exp_dir / "states" / "S000_base" / "variant" / "widths" / "links_with_width_families.gpkg")
    length_field = next(c for c in length_candidates if c in base_links.columns)

    lookup = (
        base_links[["id_link", length_field]]
        .rename(columns={length_field: "base_link_len"})
        .assign(id_link=lambda d: pd.to_numeric(d["id_link"], errors="coerce").astype("Int64"))
        .dropna(subset=["id_link"])
        .drop_duplicates(subset=["id_link"])
        .set_index("id_link")["base_link_len"]
    )
    total_len = float(lookup.sum())
    return lookup, total_len, length_field


def matched_length_from_ids(link_ids_text, base_len_lookup):
    ids = parse_int_list(link_ids_text)
    if not ids:
        return np.nan
    vals = base_len_lookup.reindex(ids)
    return float(vals.sum()) if vals.notna().any() else np.nan


def load_unit_summary(exp_dir: Path) -> pd.DataFrame:
    unit_summary = pd.read_csv(exp_dir / "states" / "S000_base" / "hierarchy" / "unit_summary.csv")
    unit_summary = unit_summary.rename(columns={"class": "unit_class"}).copy()
    unit_summary["unit_id"] = pd.to_numeric(unit_summary["unit_id"], errors="coerce").astype("Int64")
    if "compound_unit_id" in unit_summary.columns:
        unit_summary["compound_unit_id"] = pd.to_numeric(unit_summary["compound_unit_id"], errors="coerce").astype("Int64")
    return unit_summary[
        [
            "unit_id",
            "unit_class",
            "is_compound",
            "compound_unit_id",
            "compound_bubble_id",
            "in_compound_bubble",
            "compound_bubble_role",
        ]
    ].copy()


def classify_plot_category(row: pd.Series) -> str:
    if row.get("target_type") == "compound_bubble":
        return "compound unit"
    if bool(row.get("is_compound", False)):
        return "compound unit"
    if pd.notna(row.get("compound_unit_id")):
        return "part of compound unit"
    if str(row.get("unit_class", "")) == "compound_or_nested_complex":
        return "nested unit"
    return "single unit"


def build_plot_df(mode: str, exp_dir: Path) -> pd.DataFrame:
    states_dir = exp_dir / "states"

    run = pd.read_csv(exp_dir / "rapid_run_registry.csv")
    comp = pd.read_csv(exp_dir / "equivalent_resistance" / "equivalent_resistance_comparison.csv")
    matched = pd.read_csv(exp_dir / "equivalent_resistance" / "matched_base_corridors.csv")
    child = pd.read_csv(exp_dir / "equivalent_resistance" / "child_realized_objects.csv")
    unit_summary = load_unit_summary(exp_dir)

    state_ids = run.loc[run["state_id"].ne("S000_base"), "state_id"].tolist()

    base = load_outlet(states_dir, "S000_base")
    t_base = base["time_seconds"].to_numpy()
    q_base = base["q_outlet_cms"].to_numpy()
    dt_seconds = float(np.median(np.diff(t_base)))

    base_metrics = {
        "peak_time_seconds": float(t_base[np.argmax(q_base)]),
        "rise95_time_seconds": interp_first_crossing_time(t_base, q_base, 0.95 * np.max(q_base)),
        "plateau995_center_seconds": plateau_center_time(t_base, q_base, frac=0.995),
        "centroid50_seconds": weighted_centroid_time(t_base, q_base, frac=0.50),
    }

    rows = []
    for state_id in state_ids:
        df = load_outlet(states_dir, state_id)
        t = df["time_seconds"].to_numpy()
        q = df["q_outlet_cms"].to_numpy()

        metrics = {
            "state_id": state_id,
            "peak_time_seconds": float(t[np.argmax(q)]),
            "rise95_time_seconds": interp_first_crossing_time(t, q, 0.95 * np.max(q)),
            "plateau995_center_seconds": plateau_center_time(t, q, frac=0.995),
            "centroid50_seconds": weighted_centroid_time(t, q, frac=0.50),
            "xcorr_lag_hours": xcorr_lag_hours(q_base, q, dt_seconds),
        }

        for key, base_value in base_metrics.items():
            shift_name = key.replace("_seconds", "_shift_hours")
            metrics[shift_name] = (metrics[key] - base_value) / 3600.0

        rows.append(metrics)

    summary = pd.DataFrame(rows).merge(
        comp[
            [
                "state_id",
                "child_object_id",
                "target_type",
                "target_id",
                "Lambda_matched",
                "K_eq_matched_base",
                "K_variant_realized",
                "boundary_relation",
                "comparison_valid_for_matched",
            ]
        ],
        on="state_id",
        how="left",
    )

    summary = summary.loc[summary["comparison_valid_for_matched"].fillna(False)].copy()
    summary["target_id"] = pd.to_numeric(summary["target_id"], errors="coerce").astype("Int64")

    summary = (
        summary.merge(
            matched[
                [
                    "state_id",
                    "child_object_id",
                    "matched_base_link_ids",
                    "matched_base_n_links",
                    "Q_unit_matched_base",
                ]
            ],
            on=["state_id", "child_object_id"],
            how="left",
        )
        .merge(
            child[
                [
                    "state_id",
                    "child_object_id",
                    "child_link_ids",
                    "child_object_type",
                    "Q_unit_variant",
                ]
            ],
            on=["state_id", "child_object_id"],
            how="left",
        )
    )

    base_len_lookup, total_base_len, length_field = build_length_lookup(exp_dir)

    summary["matched_base_len"] = summary["matched_base_link_ids"].map(
        lambda x: matched_length_from_ids(x, base_len_lookup)
    )
    summary["matched_len_frac"] = summary["matched_base_len"] / total_base_len
    summary["neg_log10_lambda"] = -np.log10(summary["Lambda_matched"])
    summary["length_weighted_log_lambda"] = summary["matched_len_frac"] * summary["neg_log10_lambda"]

    if mode == "indep":
        summary = summary.merge(unit_summary, left_on="target_id", right_on="unit_id", how="left")
    else:
        summary["unit_id"] = pd.Series([pd.NA] * len(summary), dtype="Int64")
        summary["unit_class"] = pd.NA
        summary["is_compound"] = True
        summary["compound_unit_id"] = pd.Series([pd.NA] * len(summary), dtype="Int64")
        summary["compound_bubble_id"] = summary["target_id"]
        summary["in_compound_bubble"] = True
        summary["compound_bubble_role"] = "compound_bubble"

    summary["plot_category"] = summary.apply(classify_plot_category, axis=1)

    summary["mode"] = mode
    summary["experiment_dir"] = str(exp_dir)
    summary["base_length_field"] = length_field
    summary["example_id"] = EXAMPLE_ID
    return summary


plot_df = pd.concat(
    [build_plot_df(mode, exp_dir) for mode, exp_dir in EXPERIMENTS.items()],
    ignore_index=True,
)

fig = px.scatter(
    plot_df,
    x="length_weighted_log_lambda",
    y="centroid50_shift_hours",
    color="plot_category",
    symbol="mode",
    hover_data=[
        "state_id",
        "plot_category",
        "target_type",
        "target_id",
        "unit_class",
        "is_compound",
        "compound_unit_id",
        "compound_bubble_id",
        "compound_bubble_role",
        "child_object_id",
        "child_object_type",
        "boundary_relation",
        "Lambda_matched",
        "matched_base_len",
        "matched_len_frac",
        "K_eq_matched_base",
        "K_variant_realized",
        "peak_time_shift_hours",
        "rise95_time_shift_hours",
        "plateau995_center_shift_hours",
        "xcorr_lag_hours",
    ],
    labels={
        "length_weighted_log_lambda": "matched_len_frac * (-log10(Lambda_matched))",
        "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
        "plot_category": "Category",
        "mode": "Experiment type",
    },
    title=f"{PLOT_PREFIX}: Centroid Shift vs Length-Weighted Resistance Change",
    color_discrete_map={
        "single unit": "#1f77b4",
        "compound unit": "#d62728",
        "nested unit": "#2ca02c",
        "part of compound unit": "#ff7f0e",
    },
)

fig.update_traces(marker=dict(size=11, line=dict(width=1, color="black")))
fig.add_hline(y=0, line_dash="dash", line_color="gray")
fig.show()

plot_df[
    [
        "plot_category",
        "mode",
        "state_id",
        "target_type",
        "target_id",
        "unit_class",
        "Lambda_matched",
        "matched_base_len",
        "matched_len_frac",
        "length_weighted_log_lambda",
        "centroid50_shift_hours",
    ]
].sort_values(["plot_category", "mode", "length_weighted_log_lambda"])

,plot_category,mode,state_id,target_type,target_id,unit_class,Lambda_matched,matched_base_len,matched_len_frac,length_weighted_log_lambda,centroid50_shift_hours
22,compound unit,compound,CB006_bubble_12,compound_bubble,12,NaN,0.062119,2792.419202,0.027032,0.032622,-0.730929
21,compound unit,compound,CB005_bubble_4,compound_bubble,4,NaN,0.225054,6062.447856,0.058687,0.038013,-1.183869
20,compound unit,compound,CB004_bubble_1,compound_bubble,1,NaN,0.187423,5982.797024,0.057916,0.042115,-3.236751
23,compound unit,compound,CB007_bubble_15,compound_bubble,15,NaN,0.084208,5318.888823,0.051489,0.055333,-8.604826
18,compound unit,compound,CB002_bubble_9,compound_bubble,9,NaN,0.125700,9637.366573,0.093294,0.084027,-2.871491
19,compound unit,compound,CB003_bubble_10,compound_bubble,10,NaN,0.070675,9915.724847,0.095989,0.110458,-2.407524
17,compound unit,compound,CB001_bubble_14,compound_bubble,14,NaN,0.019319,10859.181600,0.105122,0.180182,-3.135958
14,compound unit,indep,S029_unit_10,unit,10,compound_or_nested_complex,0.184404,4702.514128,0.045523,0.033424,-0.747960
12,compound unit,indep,S023_unit_24,unit,24,compound_or_nested_complex,0.049686,3178.063814,0.030765,0.040111,0.051174
15,compound unit,indep,S030_unit_30,unit,30,compound_or_nested_complex,0.084208,5318.888823,0.051489,0.055333,-8.604826
16,compound unit,indep,S031_unit_16,unit,16,compound_or_nested_complex,0.070675,9915.724847,0.095989,0.110458,-2.407524
5,part of compound unit,indep,S007_unit_14,unit,14,simple_bifurcation_confluence_pair,0.140345,996.642748,0.009648,0.008228,-0.071996
9,part of compound unit,indep,S012_unit_25,unit,25,simple_bifurcation_confluence_pair,0.111109,1318.947448,0.012768,0.012184,-0.080683
10,part of compound unit,indep,S015_unit_17,unit,17,simple_bifurcation_confluence_pair,0.125139,1554.892455,0.015052,0.013586,-0.324571
6,part of compound unit,indep,S009_unit_31,unit,31,simple_bifurcation_confluence_pair,0.119598,1626.111897,0.015742,0.014518,-0.285059
13,part of compound unit,indep,S024_unit_15,unit,15,simple_bifurcation_confluence_pair,0.124760,2335.279219,0.022607,0.020435,-0.485119
0,single unit,indep,S001_unit_5,unit,5,simple_bifurcation_confluence_pair,0.584814,2495.522964,0.024158,0.005628,-0.330301
1,single unit,indep,S002_unit_1,unit,1,simple_bifurcation_confluence_pair,0.286998,1822.840492,0.017646,0.009566,-0.546475
2,single unit,indep,S003_unit_4,unit,4,simple_bifurcation_confluence_pair,0.291830,1851.075199,0.017919,0.009585,-0.456446
8,single unit,indep,S011_unit_3,unit,3,simple_bifurcation_confluence_pair,0.405107,2721.199760,0.026343,0.010338,-0.636659
3,single unit,indep,S004_unit_21,unit,21,simple_bifurcation_confluence_pair,0.183778,1502.258319,0.014543,0.010699,-0.440470
4,single unit,indep,S005_unit_18,unit,18,simple_bifurcation_confluence_pair,0.156730,1833.270338,0.017747,0.014284,-0.397058
7,single unit,indep,S010_unit_13,unit,13,simple_bifurcation_confluence_pair,0.335800,3328.705500,0.032223,0.015271,-0.770028
11,single unit,indep,S017_unit_7,unit,7,simple_bifurcation_confluence_pair,0.345261,4184.631891,0.040509,0.018709,-1.123805

In [241]:
from pathlib import Path
import json

import geopandas as gpd
import numpy as np
import pandas as pd
import plotly.express as px

# Requires the combined anchored plot_df from the previous section.
geom_df = plot_df.copy()

def parse_int_list(value):
    if pd.isna(value):
        return []
    text = str(value).strip()
    if not text:
        return []
    return [int(float(x.strip())) for x in text.split(",") if x.strip()]

def _first_present(columns, candidates):
    for candidate in candidates:
        if candidate in columns:
            return candidate
    return None

def _build_base_context(exp_dir: Path):
    manifest = json.loads((exp_dir / "equivalent_resistance" / "equivalent_resistance_manifest.json").read_text())
    eq_cfg = manifest["equivalent_resistance_config"]
    length_field = eq_cfg["length_field_candidates"][0]

    base_variant = gpd.read_file(exp_dir / "states" / "S000_base" / "variant" / "widths" / "links_with_width_families.gpkg")
    width_field = _first_present(base_variant.columns, eq_cfg["width_field_candidates"])
    if width_field is None:
        raise ValueError(f"Could not resolve a width field for {exp_dir}.")

    base_variant = base_variant.copy()
    base_variant["id_link"] = pd.to_numeric(base_variant["id_link"], errors="coerce").astype("Int64")
    base_variant["id_us_node"] = pd.to_numeric(base_variant["id_us_node"], errors="coerce").astype("Int64")
    base_variant["id_ds_node"] = pd.to_numeric(base_variant["id_ds_node"], errors="coerce").astype("Int64")
    base_variant[length_field] = pd.to_numeric(base_variant[length_field], errors="coerce")
    base_variant[width_field] = pd.to_numeric(base_variant[width_field], errors="coerce")
    base_variant = base_variant.dropna(subset=["id_link"]).drop_duplicates(subset=["id_link"])

    len_lookup = base_variant.set_index("id_link")[length_field]
    width_lookup = base_variant.set_index("id_link")[width_field]
    us_lookup = base_variant.set_index("id_link")["id_us_node"]
    ds_lookup = base_variant.set_index("id_link")["id_ds_node"]

    base_rapid = pd.read_csv(exp_dir / "states" / "S000_base" / "rapid" / "prep" / "rapid_link_attributes.csv")
    dist_cols = [c for c in ["parent_link_id", "network_us_dist_out_m", "network_ds_dist_out_m"] if c in base_rapid.columns]
    dist_df = base_rapid[dist_cols].copy()
    dist_df["parent_link_id"] = pd.to_numeric(dist_df["parent_link_id"], errors="coerce").astype("Int64")
    dist_df["network_us_dist_out_m"] = pd.to_numeric(dist_df["network_us_dist_out_m"], errors="coerce")
    dist_df["network_ds_dist_out_m"] = pd.to_numeric(dist_df["network_ds_dist_out_m"], errors="coerce")
    dist_df = dist_df.dropna(subset=["parent_link_id"]).drop_duplicates(subset=["parent_link_id"])
    dist_df["parent_mid_dist_out_m"] = (dist_df["network_us_dist_out_m"] + dist_df["network_ds_dist_out_m"]) / 2.0
    max_mid = float(dist_df["parent_mid_dist_out_m"].max()) if len(dist_df) else np.nan
    if pd.notna(max_mid) and max_mid > 0:
        dist_df["along_network_frac"] = dist_df["parent_mid_dist_out_m"] / max_mid
    else:
        dist_df["along_network_frac"] = np.nan
    dist_lookup = dist_df.set_index("parent_link_id")[["parent_mid_dist_out_m", "along_network_frac"]]

    return {
        "len_lookup": len_lookup,
        "width_lookup": width_lookup,
        "us_lookup": us_lookup,
        "ds_lookup": ds_lookup,
        "total_base_len": float(len_lookup.sum()),
        "dist_lookup": dist_lookup,
        "length_field": length_field,
        "width_field": width_field,
    }

def _child_length(exp_dir: Path, state_id: str, child_link_ids_text: str):
    child_link_ids = parse_int_list(child_link_ids_text)
    if not child_link_ids:
        return np.nan
    manifest = json.loads((exp_dir / "equivalent_resistance" / "equivalent_resistance_manifest.json").read_text())
    length_field = manifest["equivalent_resistance_config"]["length_field_candidates"][0]
    child_variant = gpd.read_file(exp_dir / "states" / state_id / "variant" / "widths" / "links_with_width_families.gpkg")
    child_variant = child_variant.drop_duplicates(subset=["id_link"])
    child_variant["id_link"] = pd.to_numeric(child_variant["id_link"], errors="coerce").astype("Int64")
    return float(child_variant.loc[child_variant["id_link"].isin(child_link_ids), length_field].sum())

def _width_fraction_of_total(row, ctx):
    parent_ids = parse_int_list(row.matched_base_link_ids)
    if not parent_ids:
        return np.nan

    us_lookup = ctx["us_lookup"]
    ds_lookup = ctx["ds_lookup"]
    width_lookup = ctx["width_lookup"]

    parent_us = pd.to_numeric(getattr(row, "matched_base_upstream_node", np.nan), errors="coerce")
    if pd.isna(parent_us):
        return np.nan
    parent_us = int(parent_us)

    split_ids = [pid for pid in parent_ids if pid in us_lookup.index and int(us_lookup.loc[pid]) == parent_us]
    if not split_ids:
        split_ids = parent_ids

    split_width_sum = float(width_lookup.reindex(split_ids).dropna().sum())
    if not np.isfinite(split_width_sum) or split_width_sum <= 0:
        return np.nan

    upstream_candidates = [
        pid for pid in width_lookup.index
        if pid not in parent_ids and pid in ds_lookup.index and pd.notna(ds_lookup.loc[pid]) and int(ds_lookup.loc[pid]) == parent_us
    ]
    if not upstream_candidates:
        return np.nan

    # Prefer the nearest upstream single-channel parent link using the largest distance-to-outlet midpoint.
    dist_lookup = ctx["dist_lookup"]
    ranked = []
    for pid in upstream_candidates:
        if pid in dist_lookup.index and pd.notna(dist_lookup.loc[pid, "parent_mid_dist_out_m"]):
            ranked.append((float(dist_lookup.loc[pid, "parent_mid_dist_out_m"]), pid))
        else:
            ranked.append((float("-inf"), pid))
    upstream_pid = max(ranked)[1]
    upstream_width = float(width_lookup.get(upstream_pid, np.nan))
    if not np.isfinite(upstream_width) or upstream_width <= 0:
        return np.nan

    return float(min(split_width_sum / upstream_width, 1.0))

contexts = {}
matched_meta = []
for exp_dir_str in geom_df["experiment_dir"].dropna().unique():
    exp_dir = Path(exp_dir_str)
    contexts[str(exp_dir)] = _build_base_context(exp_dir)
    matched_meta.append(
        pd.read_csv(exp_dir / "equivalent_resistance" / "matched_base_corridors.csv")[[
            "state_id",
            "child_object_id",
            "matched_base_upstream_node",
            "matched_base_downstream_node",
        ]]
    )

matched_meta = pd.concat(matched_meta, ignore_index=True).drop_duplicates(subset=["state_id", "child_object_id"])
geom_df = geom_df.merge(matched_meta, on=["state_id", "child_object_id"], how="left")

matched_lens = []
matched_dist_mid = []
matched_dist_frac = []
child_lens = []
width_fracs = []

for row in geom_df.itertuples(index=False):
    exp_dir = Path(row.experiment_dir)
    ctx = contexts[str(exp_dir)]
    len_lookup = ctx["len_lookup"]
    dist_lookup = ctx["dist_lookup"]
    total_base_len = ctx["total_base_len"]

    parent_ids = parse_int_list(row.matched_base_link_ids)
    parent_series = len_lookup.reindex(parent_ids)
    matched_base_len = float(parent_series.sum()) if len(parent_ids) else np.nan
    matched_lens.append(matched_base_len)

    if len(parent_ids):
        dist_frame = dist_lookup.reindex(parent_ids).reset_index()
        dist_frame["base_link_len"] = parent_series.values
        dist_frame = dist_frame.dropna(subset=["base_link_len"])
        weight_sum = float(dist_frame["base_link_len"].sum()) if len(dist_frame) else np.nan
        if len(dist_frame) and pd.notna(weight_sum) and weight_sum > 0:
            matched_dist_mid.append(float(np.average(dist_frame["parent_mid_dist_out_m"], weights=dist_frame["base_link_len"])))
            matched_dist_frac.append(float(np.average(dist_frame["along_network_frac"], weights=dist_frame["base_link_len"])))
        else:
            matched_dist_mid.append(np.nan)
            matched_dist_frac.append(np.nan)
    else:
        matched_dist_mid.append(np.nan)
        matched_dist_frac.append(np.nan)

    child_lens.append(_child_length(exp_dir, row.state_id, row.child_link_ids))
    width_fracs.append(_width_fraction_of_total(row, ctx))

geom_df["matched_base_len"] = matched_lens
geom_df["along_network_mid_dist_out_m"] = matched_dist_mid
geom_df["along_network_frac"] = matched_dist_frac
geom_df["child_len"] = child_lens
geom_df["child_parent_len_frac"] = geom_df["child_len"] / geom_df["matched_base_len"]
geom_df["width_fraction_of_total"] = width_fracs
geom_df["child_parent_weighted_log_lambda"] = geom_df["child_parent_len_frac"] * geom_df["neg_log10_lambda"]
geom_df["child_parent_width_weighted_log_lambda"] = (
    geom_df["child_parent_len_frac"]
    * geom_df["neg_log10_lambda"]
    * geom_df["width_fraction_of_total"]
)

geom_df[[
    "mode",
    "state_id",
    "target_type",
    "target_id",
    "Lambda_matched",
    "matched_base_len",
    "child_len",
    "matched_len_frac",
    "child_parent_len_frac",
    "width_fraction_of_total",
    "along_network_frac",
    "length_weighted_log_lambda",
    "child_parent_weighted_log_lambda",
    "child_parent_width_weighted_log_lambda",
    "centroid50_shift_hours",
]].sort_values(["mode", "target_type", "target_id"])

,mode,state_id,target_type,target_id,Lambda_matched,matched_base_len,child_len,matched_len_frac,child_parent_len_frac,width_fraction_of_total,along_network_frac,length_weighted_log_lambda,child_parent_weighted_log_lambda,child_parent_width_weighted_log_lambda,centroid50_shift_hours
20,compound,CB004_bubble_1,compound_bubble,1,0.187423,5982.797024,2461.763930,0.057916,0.411474,1.000000,0.965273,0.042115,0.299214,0.299214,-3.236751
21,compound,CB005_bubble_4,compound_bubble,4,0.225054,6062.447856,2337.667898,0.058687,0.385598,1.000000,0.701924,0.038013,0.249757,0.249757,-1.183869
18,compound,CB002_bubble_9,compound_bubble,9,0.125700,9637.366573,3615.077209,0.093294,0.375110,1.000000,0.483404,0.084027,0.337849,0.337849,-2.871491
19,compound,CB003_bubble_10,compound_bubble,10,0.070675,9915.724847,3753.142824,0.095989,0.378504,1.000000,0.354491,0.110458,0.435558,0.435558,-2.407524
22,compound,CB006_bubble_12,compound_bubble,12,0.062119,2792.419202,963.892746,0.027032,0.345182,1.000000,0.290438,0.032622,0.416558,0.416558,-0.730929
17,compound,CB001_bubble_14,compound_bubble,14,0.019319,10859.181600,2788.032067,0.105122,0.256744,1.000000,0.208142,0.180182,0.440065,0.440065,-3.135958
23,compound,CB007_bubble_15,compound_bubble,15,0.084208,5318.888823,2031.835754,0.051489,0.382004,1.000000,0.130342,0.055333,0.410519,0.410519,-8.604826
1,indep,S002_unit_1,unit,1,0.286998,1822.840492,729.912721,0.017646,0.400426,1.000000,0.618754,0.009566,0.217079,0.217079,-0.546475
8,indep,S011_unit_3,unit,3,0.405107,2721.199760,1247.061854,0.026343,0.458276,1.000000,0.647778,0.010338,0.179842,0.179842,-0.636659
2,indep,S003_unit_4,unit,4,0.291830,1851.075199,759.365438,0.017919,0.410229,1.000000,0.589516,0.009585,0.219420,0.219420,-0.456446
0,indep,S001_unit_5,unit,5,0.584814,2495.522964,941.929338,0.024158,0.377448,1.000000,0.567113,0.005628,0.087939,0.087939,-0.330301
11,indep,S017_unit_7,unit,7,0.345261,4184.631891,1824.919766,0.040509,0.436100,1.000000,0.804893,0.018709,0.201414,0.201414,-1.123805
14,indep,S029_unit_10,unit,10,0.184404,4702.514128,1954.963824,0.045523,0.415727,1.000000,0.467261,0.033424,0.305240,0.305240,-0.747960
7,indep,S010_unit_13,unit,13,0.335800,3328.705500,1459.435218,0.032223,0.438439,1.000000,0.929782,0.015271,0.207785,0.207785,-0.770028
5,indep,S007_unit_14,unit,14,0.140345,996.642748,459.690298,0.009648,0.461239,1.000000,0.458295,0.008228,0.393345,0.393345,-0.071996
13,indep,S024_unit_15,unit,15,0.124760,2335.279219,1071.906444,0.022607,0.459006,1.000000,0.361258,0.020435,0.414907,0.414907,-0.485119
16,indep,S031_unit_16,unit,16,0.070675,9915.724847,3753.142824,0.095989,0.378504,1.000000,0.354491,0.110458,0.435558,0.435558,-2.407524
10,indep,S015_unit_17,unit,17,0.125139,1554.892455,690.339563,0.015052,0.443979,1.000000,0.336096,0.013586,0.400739,0.400739,-0.324571
4,indep,S005_unit_18,unit,18,0.156730,1833.270338,797.801402,0.017747,0.435179,0.993032,0.310192,0.014284,0.350253,0.347812,-0.397058
3,indep,S004_unit_21,unit,21,0.183778,1502.258319,599.074351,0.014543,0.398783,0.855336,0.254422,0.010699,0.293387,0.250945,-0.440470
12,indep,S023_unit_24,unit,24,0.049686,3178.063814,903.850120,0.030765,0.284403,1.000000,0.202547,0.040111,0.370794,0.370794,0.051174
9,indep,S012_unit_25,unit,25,0.111109,1318.947448,583.624693,0.012768,0.442493,0.828233,0.201478,0.012184,0.422249,0.349721,-0.080683
15,indep,S030_unit_30,unit,30,0.084208,5318.888823,2031.835754,0.051489,0.382004,1.000000,0.130342,0.055333,0.410519,0.410519,-8.604826
6,indep,S009_unit_31,unit,31,0.119598,1626.111897,711.556002,0.015742,0.437581,1.000000,0.127089,0.014518,0.403571,0.403571,-0.285059

In [242]:
hover_cols = [
    "state_id",
    "plot_category",
    "mode",
    "target_type",
    "target_id",
    "unit_class",
    "compound_unit_id",
    "compound_bubble_id",
    "boundary_relation",
    "Lambda_matched",
    "matched_base_len",
    "child_len",
    "matched_len_frac",
    "child_parent_len_frac",
    "width_fraction_of_total",
    "along_network_frac",
    "peak_time_shift_hours",
    "rise95_time_shift_hours",
    "plateau995_center_shift_hours",
    "xcorr_lag_hours",
]

fig = px.scatter(
    geom_df,
    x="length_weighted_log_lambda",
    y="centroid50_shift_hours",
    color="along_network_frac",
    symbol="mode",
    hover_data=hover_cols,
    labels={
        "length_weighted_log_lambda": "matched_len_frac * (-log10(Lambda_matched))",
        "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
        "along_network_frac": "Along-network fractional distance",
    },
    title="56 anchored: Centroid Shift vs Length-Weighted Resistance Change, colored by along-network distance",
    color_continuous_scale="Viridis",
)
fig.update_traces(marker=dict(size=11, line=dict(width=1, color="black")))
fig.add_hline(y=0, line_dash="dash", line_color="gray")
fig.show()

fig = px.scatter(
    geom_df,
    x="child_parent_weighted_log_lambda",
    y="centroid50_shift_hours",
    color="plot_category",
    symbol="mode",
    hover_data=hover_cols,
    labels={
        "child_parent_weighted_log_lambda": "(child_len / matched_parent_len) * (-log10(Lambda_matched))",
        "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
        "plot_category": "Category",
        "mode": "Experiment type",
    },
    title="56 anchored: Centroid Shift vs Child/Parent-Length-Weighted Resistance Change",
    color_discrete_map={
        "single unit": "#1f77b4",
        "compound unit": "#d62728",
        "nested unit": "#2ca02c",
        "part of compound unit": "#ff7f0e",
    },
)
fig.update_traces(marker=dict(size=11, line=dict(width=1, color="black")))
fig.add_hline(y=0, line_dash="dash", line_color="gray")
fig.show()

fig = px.scatter(
    geom_df,
    x="child_parent_width_weighted_log_lambda",
    y="centroid50_shift_hours",
    color="plot_category",
    symbol="mode",
    hover_data=hover_cols,
    labels={
        "child_parent_width_weighted_log_lambda": "(child_len / matched_parent_len) * (-log10(Lambda_matched)) * width_fraction_of_total",
        "centroid50_shift_hours": "Centroid shift above 50% peak [hours]",
        "plot_category": "Category",
        "mode": "Experiment type",
    },
    title="56 anchored: Centroid Shift vs Width-Adjusted Child/Parent-Length-Weighted Resistance Change",
    color_discrete_map={
        "single unit": "#1f77b4",
        "compound unit": "#d62728",
        "nested unit": "#2ca02c",
        "part of compound unit": "#ff7f0e",
    },
)
fig.update_traces(marker=dict(size=11, line=dict(width=1, color="black")))
fig.add_hline(y=0, line_dash="dash", line_color="gray")
fig.show()

In [ ]:
import sys
from pathlib import Path

RAPID_SRC = Path.cwd() / "RAPID" / "src"
if str(RAPID_SRC) not in sys.path:
    sys.path.append(str(RAPID_SRC))

from rapid_tools import (
    build_geometry_context_frame,
    build_multi_example_timing_frame,
    make_timing_scatter,
    supported_timing_metrics,
)

EXAMPLE_IDS = ["56"]
Y_METRIC = "centroid50_shift_hours"

print("Available timing metrics:")
for key, label in supported_timing_metrics().items():
    print(f"- {key}: {label}")

plot_df = build_multi_example_timing_frame(EXAMPLE_IDS)
geom_df = build_geometry_context_frame(plot_df)
example_label = ", ".join(EXAMPLE_IDS)
hover_fields = ["example_id", "target_id"]

fig = make_timing_scatter(
    geom_df,
    x="length_weighted_log_lambda",
    y=Y_METRIC,
    color="along_network_frac",
    symbol="mode",
    hover_fields=hover_fields,
    title=f"Examples {example_label}: {supported_timing_metrics()[Y_METRIC]} vs length-weighted log lambda",
)
fig.show()

fig = make_timing_scatter(
    geom_df,
    x="child_parent_weighted_log_lambda",
    y=Y_METRIC,
    color="plot_category",
    symbol="mode",
    hover_fields=hover_fields,
    title=f"Examples {example_label}: {supported_timing_metrics()[Y_METRIC]} vs child/parent-length-weighted log lambda",
)
fig.show()

fig = make_timing_scatter(
    geom_df,
    x="child_parent_width_weighted_log_lambda",
    y=Y_METRIC,
    color="plot_category",
    symbol="mode",
    hover_fields=hover_fields,
    title=f"Examples {example_label}: {supported_timing_metrics()[Y_METRIC]} vs width-adjusted child/parent-length-weighted log lambda",
)
fig.show()

# Look at hydrograph

In [11]:
from pathlib import Path
import json

import pandas as pd
import plotly.graph_objects as go

# ----------------------------
# paths
# ----------------------------
repo_root = Path("/Users/6256481/Code/river-hierarchy")

example_id = 2
if example_id <10:
    exid = f'0{example_id}'
variant_root = repo_root / f"network_variants/output/{exid}_indep__anchored"
first_n_units = 5

mask_xlsx = repo_root / "SWORD_gauge_match/outputs/mask_hydro_quality.xlsx"

timeseries_paths = [
    repo_root / "SWORD_gauge_match/outputs/subdaily_timeseries.csv",
    repo_root / "SWORD_gauge_match/outputs/subdaily_timeseries.parquet",
    repo_root / "SWORD_gauge_match/outputs/gauge_timeseries.parquet",
    repo_root / "SWORD_gauge_match/outputs/grdc_timeseries.parquet",
]

for p in timeseries_paths:
    print(p, p.exists())


# ----------------------------
# helpers
# ----------------------------
def load_quality_row(example_id: int, mask_xlsx: Path) -> pd.Series:
    quality = pd.read_excel(mask_xlsx, sheet_name="Hydrograph_quality")
    row = quality.loc[quality["Example"] == example_id]
    if row.empty:
        raise ValueError(f"No row found for Example={example_id}")
    return row.iloc[0]

def load_station_timeseries(station_key: str, paths: list[Path]) -> pd.DataFrame:
    print(f"looking for {station_key}")
    for path in paths:
        print("  ", path, path.exists())

    
    frames = []

    for path in paths:
        if not path.exists():
            continue

        try:
            if path.suffix == ".csv":
                df = pd.read_csv(path)
            elif path.suffix == ".parquet":
                try:
                    df = pd.read_parquet(path, filters=[("station_key", "==", station_key)])
                except Exception:
                    df = pd.read_parquet(path)
            else:
                continue
        except Exception:
            continue

        if "station_key" not in df.columns:
            continue

        df = df.loc[df["station_key"].astype(str) == station_key].copy()
        if df.empty:
            continue

        if "discharge_cms" in df.columns and "discharge" not in df.columns:
            df = df.rename(columns={"discharge_cms": "discharge"})

        if "time" not in df.columns or "discharge" not in df.columns:
            continue

        df["time"] = pd.to_datetime(df["time"], utc=True, errors="coerce")
        df["discharge"] = pd.to_numeric(df["discharge"], errors="coerce")
        df = df.dropna(subset=["time", "discharge"])

        frames.append(df[["station_key", "time", "discharge"]])

    if not frames:
        raise ValueError(f"No timeseries found for station {station_key}")

    return (
        pd.concat(frames, ignore_index=True)
        .sort_values("time")
        .drop_duplicates(subset=["station_key", "time"], keep="first")
        .reset_index(drop=True)
    )

def load_anchored_unit_hydros(variant_root: Path, first_n_units=None) -> list[tuple[str, pd.DataFrame]]:
    states_dir = variant_root / "states"

    base_dir = states_dir / "S000_base"
    unit_dirs = sorted(
        p for p in states_dir.iterdir()
        if p.is_dir() and p.name != "S000_base"
    )

    if first_n_units is not None:
        unit_dirs = unit_dirs[:first_n_units]

    state_dirs = []
    if base_dir.exists():
        state_dirs.append(base_dir)
    state_dirs.extend(unit_dirs)

    hydros = []
    for state_dir in state_dirs:
        manifest_path = state_dir / "variant/summary/variant_manifest.json"
        hydro_path = state_dir / "rapid/run/outlet_hydrograph.csv"

        if not manifest_path.exists() or not hydro_path.exists():
            continue

        manifest = json.loads(manifest_path.read_text())
        selected_units = manifest.get("selected_unit_ids", [])

        if state_dir.name == "S000_base":
            label = "S000_base"
        else:
            label = f"{state_dir.name} | unit={selected_units[0] if selected_units else 'NA'}"

        hydro = pd.read_csv(hydro_path)
        hydro["time_utc"] = pd.to_datetime(hydro["time_utc"], utc=True, errors="coerce")
        hydro["q_outlet_cms"] = pd.to_numeric(hydro["q_outlet_cms"], errors="coerce")
        hydro = hydro.dropna(subset=["time_utc", "q_outlet_cms"])

        hydros.append((label, hydro))

    return hydros


# ----------------------------
# load workbook info
# ----------------------------
row = load_quality_row(example_id, mask_xlsx)

up_station = row["Up"]
down_station = row["Down"]
period_start = pd.to_datetime(row["Period_start"], utc=True)
period_end = pd.to_datetime(row["Period_end"], utc=True)

print("Up:", up_station)
print("Down:", down_station)
print("Period:", period_start, "to", period_end)

# ----------------------------
# load observed gauge hydrographs
# ----------------------------
up_ts = load_station_timeseries(up_station, timeseries_paths)
down_ts = load_station_timeseries(down_station, timeseries_paths)

up_ts = up_ts.loc[up_ts["time"].between(period_start, period_end)].copy()
down_ts = down_ts.loc[down_ts["time"].between(period_start, period_end)].copy()

# ----------------------------
# plot 1: Up vs Down gauges
# ----------------------------
fig1 = go.Figure()

fig1.add_trace(go.Scatter(
    x=up_ts["time"], y=up_ts["discharge"],
    mode="lines", name=f"Up gauge ({up_station})"
))
fig1.add_trace(go.Scatter(
    x=down_ts["time"], y=down_ts["discharge"],
    mode="lines", name=f"Down gauge ({down_station})"
))

fig1.update_layout(
    title=f"Example {example_id}: observed Up vs Down hydrograph",
    xaxis_title="Time (UTC)",
    yaxis_title="Discharge (m³/s)",
    template="plotly_white",
    hovermode="x unified",
)
fig1.show()

# ----------------------------
# plot 2: Up gauge vs anchored RAPID units
# ----------------------------
unit_hydros = load_anchored_unit_hydros(variant_root, first_n_units=first_n_units)

base_manifest_path = variant_root / "states" / "S000_base" / "rapid" / "prep" / "rapid_prep_manifest.json"
base_manifest = json.loads(base_manifest_path.read_text())

forcing_meta = base_manifest.get("forcing_metadata", {}) or {}
spinup_hours = float(forcing_meta.get("spinup_hours", 0.0) or 0.0)

rapid_plot_start = period_start - pd.Timedelta(hours=spinup_hours)
rapid_plot_end = period_end + pd.Timedelta(hours=spinup_hours)

print("spinup_hours used for plotting:", spinup_hours)
print("rapid plot window:", rapid_plot_start, "to", rapid_plot_end)



fig2 = go.Figure()

fig2.add_trace(go.Scatter(
    x=up_ts["time"],
    y=up_ts["discharge"],
    mode="lines",
    name=f"Observed Up ({up_station})",
    line=dict(color="black", width=3)
))

for label, hydro in unit_hydros:
    hydro = hydro.loc[hydro["time_utc"].between(rapid_plot_start, rapid_plot_end)].copy()
    fig2.add_trace(go.Scatter(
        x=hydro["time_utc"],
        y=hydro["q_outlet_cms"],
        mode="lines",
        name=label,
        opacity=0.7
    ))

fig2.add_vline(x=period_start, line_dash="dash", line_color="gray")
fig2.show()

/Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/subdaily_timeseries.csv True
/Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/subdaily_timeseries.parquet True
/Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/gauge_timeseries.parquet True
/Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/grdc_timeseries.parquet True
Up: CL:3179520
Down: CL:3179500
Period: 2025-07-26 00:01:00+00:00 to 2026-08-10 00:00:00+00:00
looking for CL:3179520
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/subdaily_timeseries.csv True
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/subdaily_timeseries.parquet True
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/gauge_timeseries.parquet True
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/grdc_timeseries.parquet True

/var/folders/bs/xx1t3fn91jl3k26fn1pndd_c0000gn/T/ipykernel_11920/3446738122.py:55: DtypeWarning: Columns (1,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

looking for CL:3179500
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/subdaily_timeseries.csv True
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/subdaily_timeseries.parquet True
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/gauge_timeseries.parquet True
   /Users/6256481/Code/river-hierarchy/SWORD_gauge_match/outputs/grdc_timeseries.parquet True

/var/folders/bs/xx1t3fn91jl3k26fn1pndd_c0000gn/T/ipykernel_11920/3446738122.py:55: DtypeWarning: Columns (1,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

spinup_hours used for plotting: 289.47872028284263
rapid plot window: 2025-07-13 22:32:16.606981767+00:00 to 2026-08-22 01:28:43.393018233+00:00

In [19]:
import math

# ----------------------------
# inputs for example 56
# ----------------------------

# Reference-section values from:
# network_variants/output/56_indep__anchored/reference_section/reference_section_summary.json
# network_variants/output/56_indep__anchored/reference_section/reference_kb_summary.json

slope = 0.00023841392154989668
n_manning = 0.35
kb_current = 446.8203057313246

# Choose which width you want to use.
# Option 1: summary reference width from reference_section_summary.json
width_ref_m = 1268.1302871440237

# Option 2: single-link wet width from reference-section width table
# width_ref_m = 817.559293

# Observed lag from gauges for example 56
lag_hours = 14 + 40 / 60
lag_seconds = lag_hours * 3600

# Two distance choices
distance_straight_m = 63343.62945931269   # straight-line gauge spacing
distance_network_m = 104089.415256        # full modeled network length

# ----------------------------
# helpers
# ----------------------------
def rapid_celerity(width_m, slope, kb, n):
    return (5.0 / (3.0 * n)) * math.sqrt(slope) * ((width_m ** (2.0 / 3.0)) / (kb ** (2.0 / 3.0)))

def kb_for_target_celerity(width_m, slope, c_target, n):
    a = (5.0 / (3.0 * n)) * math.sqrt(slope) * (width_m ** (2.0 / 3.0))
    return (a / c_target) ** (3.0 / 2.0)

# ----------------------------
# calculations
# ----------------------------
c_current = rapid_celerity(width_ref_m, slope, kb_current, n_manning)

c_target_straight = distance_straight_m / lag_seconds
c_target_network = distance_network_m / lag_seconds

kb_needed_straight = kb_for_target_celerity(width_ref_m, slope, c_target_straight, n_manning)
kb_needed_network = kb_for_target_celerity(width_ref_m, slope, c_target_network, n_manning)

# ----------------------------
# output
# ----------------------------
print(f"Reference width used: {width_ref_m:.3f} m")
print(f"Slope used: {slope:.9f}")
print(f"Manning n used: {n_manning:.3f}")
print(f"Current kb: {kb_current:.3f}")
print()

print(f"Current reference-centerline celerity: {c_current:.3f} m/s")
print()

print(f"Observed lag: {lag_hours:.3f} h")
print(f"Target celerity from straight-line distance ({distance_straight_m/1000:.2f} km): {c_target_straight:.3f} m/s")
print(f"Target celerity from network length ({distance_network_m/1000:.2f} km): {c_target_network:.3f} m/s")
print()

print(f"kb needed for straight-line target celerity: {kb_needed_straight:.3f}")
print(f"kb needed for network-length target celerity: {kb_needed_network:.3f}")

Reference width used: 1268.130 m
Slope used: 0.000238414
Manning n used: 0.350
Current kb: 446.820

Current reference-centerline celerity: 0.147 m/s

Observed lag: 14.667 h
Target celerity from straight-line distance (63.34 km): 1.200 m/s
Target celerity from network length (104.09 km): 1.971 m/s

kb needed for straight-line target celerity: 19.241
kb needed for network-length target celerity: 9.134

# Plot RAPID hydrograph vs Geometry

In [134]:
import sys
import importlib
from pathlib import Path

def find_repo_root(start: Path) -> Path:
    for path in [start, *start.parents]:
        if (path / "RAPID" / "src" / "rapid_tools").exists():
            return path
    raise FileNotFoundError("Could not find repo root containing RAPID/src/rapid_tools")

REPO_ROOT = find_repo_root(Path.cwd().resolve())
RAPID_SRC = REPO_ROOT / "RAPID" / "src"

if str(RAPID_SRC) not in sys.path:
    sys.path.append(str(RAPID_SRC))

if "rapid_tools" in sys.modules:
    importlib.reload(sys.modules["rapid_tools"])

from rapid_tools import (
    build_multi_example_timing_frame,
    build_geometry_context_frame,
    make_timing_scatter,
    supported_timing_x_metrics,
    supported_timing_y_metrics,
)




example_ids = ["56", "03", "02", "05","13", "21"]
example_ids = ["05", "21"]

In [135]:
display(supported_timing_x_metrics())
display(supported_timing_y_metrics())

{'along_network_frac': 'Along-network fractional distance',
 'downstream_network_distance_m': 'Downstream network distance to outlet [m]',
 'matched_len_frac': 'Matched parent length fraction of network',
 'length_fraction': 'Selected length fraction',
 'len_fraction': 'Selected length fraction',
 'child_parent_len_frac': 'Child length / matched parent length',
 'child_length_fraction': 'Child length / matched parent length',
 'width_fraction_of_total': 'Upstream width-share routed into target object',
 'width_fraction': 'Upstream width-share routed into target object',
 'Lambda_matched': 'Lambda_matched',
 'lambda_matched': 'Lambda_matched',
 'neg_log10_lambda': '-log10(Lambda_matched)',
 'log_lambda': '-log10(Lambda_matched)',
 'length_weighted_log_lambda': 'Selected length fraction * (-log10(Lambda_matched))',
 'len_fraction_weighted_log_lambda': 'Selected length fraction * (-log10(Lambda_matched))',
 'width_weighted_log_lambda': 'Selected length fraction * (-log10(Lambda_matched)) * width_fraction',
 'len_fraction_width_weighted_log_lambda': 'Selected length fraction * (-log10(Lambda_matched)) * width_fraction',
 'child_parent_weighted_log_lambda': '(child_len / matched_parent_len) * (-log10(Lambda_matched))',
 'child_parent_width_weighted_log_lambda': '(child_len / matched_parent_len) * (-log10(Lambda_matched)) * width_fraction',
 'k_ratio_to_matched_base': 'K_variant_realized / K_eq_matched_base'}

{'centroid50_shift_hours': 'Centroid shift above 50% peak [hours]',
 'centroid75_shift_hours': 'Centroid shift above 75% peak [hours]',
 'peak_time_shift_hours': 'Peak-time shift [hours]',
 'rise95_time_shift_hours': 'Rise-95 timing shift [hours]',
 'plateau995_center_shift_hours': '99.5% peak-plateau center shift [hours]',
 'peak_window_center95_shift_hours': '95% peak-window center shift [hours]',
 'peak_window_centroid95_shift_hours': '95% peak-window centroid shift [hours]',
 'xcorr_lag_hours': 'Cross-correlation lag [hours]',
 'delta_peak_time_hours': 'Peak-time delta vs base [hours]',
 'delta_lag_to_inflow_peak_hours': 'Lag-to-inflow-peak delta vs base [hours]',
 'hydrograph_lag_vs_base_hours': 'Hydrograph lag vs base [hours]',
 'lag_to_inflow_peak_relative_to_base': 'Lag-to-inflow-peak relative change vs base',
 'lag_to_inflow_peak_pct_shift_vs_base': 'Lag-to-inflow-peak percent shift vs base [%]',
 'lag_to_inflow_peak_hour_shift_vs_base': 'Lag-to-inflow-peak hour shift vs base [hours]',
 'lag_to_inflow_peak_hour_shift_vs_observed_peak': 'Lag-to-inflow-peak hour shift vs observed gauge peak lag [hours]',
 'unit_to_bubble_lag_to_inflow_peak_relative': 'Lag-to-inflow-peak relative change vs matching compound',
 'unit_to_bubble_lag_to_inflow_peak_pct_shift': 'Lag-to-inflow-peak percent shift vs matching compound [%]'}

In [136]:

plot_df = build_multi_example_timing_frame(example_ids)
geom_df = build_geometry_context_frame(plot_df, #matched_parent_vs_network, child_vs_matched_parent
                                       length_mode="matched_parent_vs_network")

D = geom_df.copy()
D["max_unit_downstream_order"] = (
    D.groupby("example_id")["compound_downstream_order"]
     .transform("max")
)
D = D[(D['compound_downstream_order'] >1) & 
      (D['compound_downstream_order'] < D["max_unit_downstream_order"])]

In [138]:
for px in ['Lambda_matched','neg_log10_lambda', 'width_fraction_of_total','length_fraction', 'child_parent_len_frac', 
           'len_fraction_width_weighted_log_lambda']:
    fig = make_timing_scatter(
        D,
        x=px,
        y="lag_to_inflow_peak_pct_shift_vs_base",
        color="plot_category",
        symbol="mode",
        hover_fields=["example_id", "target_id", "state_id"],
    )
    fig.show()

In [139]:
fig = make_timing_scatter(
        D,
        x='len_fraction_width_weighted_log_lambda',
        y="lag_to_inflow_peak_hour_shift_vs_observed_peak",
        color="plot_category",
        symbol="mode",
        hover_fields=["example_id", "target_id", "state_id"],
    )
fig.show()